// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type ShopOrdersStatus string

const (
	ShopOrdersStatusAWAITINGPAYMENT ShopOrdersStatus = "AWAITING_PAYMENT"
	ShopOrdersStatusPROCESSING      ShopOrdersStatus = "PROCESSING"
	ShopOrdersStatusSHIPPED         ShopOrdersStatus = "SHIPPED"
	ShopOrdersStatusCOMPLETED       ShopOrdersStatus = "COMPLETED"
	ShopOrdersStatusCANCELLED       ShopOrdersStatus = "CANCELLED"
	ShopOrdersStatusREFUNDED        ShopOrdersStatus = "REFUNDED"
)

func (e *ShopOrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopOrdersStatus(s)
	case string:
		*e = ShopOrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopOrdersStatus: %T", src)
	}
	return nil
}

type NullShopOrdersStatus struct {
	ShopOrdersStatus ShopOrdersStatus `json:"shop_orders_status"`
	Valid            bool             `json:"valid"` // Valid is true if ShopOrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShopOrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopOrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopOrdersStatus), nil
}

type UserVouchersStatus string

const (
	UserVouchersStatusAVAILABLE UserVouchersStatus = "AVAILABLE"
	UserVouchersStatusUSED      UserVouchersStatus = "USED"
	UserVouchersStatusEXPIRED   UserVouchersStatus = "EXPIRED"
)

func (e *UserVouchersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserVouchersStatus(s)
	case string:
		*e = UserVouchersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserVouchersStatus: %T", src)
	}
	return nil
}

type NullUserVouchersStatus struct {
	UserVouchersStatus UserVouchersStatus `json:"user_vouchers_status"`
	Valid              bool               `json:"valid"` // Valid is true if UserVouchersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserVouchersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserVouchersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserVouchersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserVouchersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserVouchersStatus), nil
}

type VouchersAppliesToType string

const (
	VouchersAppliesToTypeORDERTOTAL  VouchersAppliesToType = "ORDER_TOTAL"
	VouchersAppliesToTypeSHIPPINGFEE VouchersAppliesToType = "SHIPPING_FEE"
)

func (e *VouchersAppliesToType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersAppliesToType(s)
	case string:
		*e = VouchersAppliesToType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersAppliesToType: %T", src)
	}
	return nil
}

type NullVouchersAppliesToType struct {
	VouchersAppliesToType VouchersAppliesToType `json:"vouchers_applies_to_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if VouchersAppliesToType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersAppliesToType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersAppliesToType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersAppliesToType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersAppliesToType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersAppliesToType), nil
}

type VouchersAudienceType string

const (
	VouchersAudienceTypePUBLIC   VouchersAudienceType = "PUBLIC"
	VouchersAudienceTypeASSIGNED VouchersAudienceType = "ASSIGNED"
)

func (e *VouchersAudienceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersAudienceType(s)
	case string:
		*e = VouchersAudienceType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersAudienceType: %T", src)
	}
	return nil
}

type NullVouchersAudienceType struct {
	VouchersAudienceType VouchersAudienceType `json:"vouchers_audience_type"`
	Valid                bool                 `json:"valid"` // Valid is true if VouchersAudienceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersAudienceType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersAudienceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersAudienceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersAudienceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersAudienceType), nil
}

type VouchersDiscountType string

const (
	VouchersDiscountTypePERCENTAGE  VouchersDiscountType = "PERCENTAGE"
	VouchersDiscountTypeFIXEDAMOUNT VouchersDiscountType = "FIXED_AMOUNT"
)

func (e *VouchersDiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersDiscountType(s)
	case string:
		*e = VouchersDiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersDiscountType: %T", src)
	}
	return nil
}

type NullVouchersDiscountType struct {
	VouchersDiscountType VouchersDiscountType `json:"vouchers_discount_type"`
	Valid                bool                 `json:"valid"` // Valid is true if VouchersDiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersDiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersDiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersDiscountType), nil
}

type VouchersOwnerType string

const (
	VouchersOwnerTypePLATFORM VouchersOwnerType = "PLATFORM"
	VouchersOwnerTypeSHOP     VouchersOwnerType = "SHOP"
)

func (e *VouchersOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VouchersOwnerType(s)
	case string:
		*e = VouchersOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for VouchersOwnerType: %T", src)
	}
	return nil
}

type NullVouchersOwnerType struct {
	VouchersOwnerType VouchersOwnerType `json:"vouchers_owner_type"`
	Valid             bool              `json:"valid"` // Valid is true if VouchersOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVouchersOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.VouchersOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VouchersOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVouchersOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VouchersOwnerType), nil
}

// Bảng chứa các sản phẩm chi tiết trong một đơn hàng của shop
type OrderItems struct {
	// UUID, Khóa chính của item
	ID string `json:"id"`
	// Khóa ngoại, liên kết tới đơn hàng của shop
	ShopOrderID string `json:"shop_order_id"`
	// UUID của sản phẩm gốc
	ProductID string `json:"product_id"`
	// UUID của biến thể sản phẩm (SKU) gốc
	SkuID string `json:"sku_id"`
	// Số lượng sản phẩm được mua
	Quantity uint32 `json:"quantity"`
	// Giá gốc của 1 sản phẩm (trước khi giảm)
	OriginalUnitPrice string `json:"original_unit_price"`
	// Giá bán cuối cùng của 1 sản phẩm (sau khi giảm)
	FinalUnitPrice string `json:"final_unit_price"`
	// Tổng tiền cho item này (final_unit_price * quantity)
	TotalPrice string `json:"total_price"`
	// Bản ghi nhanh các chương trình khuyến mãi đã áp dụng dạng JSON
	PromotionsSnapshot json.RawMessage `json:"promotions_snapshot"`
	// Tên sản phẩm tại thời điểm mua
	ProductNameSnapshot string `json:"product_name_snapshot"`
	// URL hình ảnh sản phẩm tại thời điểm mua
	ProductImageSnapshot sql.NullString `json:"product_image_snapshot"`
	// Các thuộc tính của SKU (Màu, Size...) tại thời điểm mua
	SkuAttributesSnapshot sql.NullString `json:"sku_attributes_snapshot"`
}

// Bảng chứa các đơn hàng tổng của khách hàng (một lần checkout)
type Orders struct {
	// UUID, Khóa chính của đơn hàng tổng
	ID string `json:"id"`
	// Mã đơn hàng duy nhất, thân thiện với người dùng (ví dụ: YAN20251013ABC)
	OrderCode string `json:"order_code"`
	// UUID của người dùng đặt hàng
	UserID string `json:"user_id"`
	// Số tiền cuối cùng khách hàng thực trả sau khi áp dụng tất cả giảm giá và phí ship
	GrandTotal string `json:"grand_total"`
	// Tổng tiền hàng gốc của tất cả sản phẩm từ tất cả các shop
	Subtotal string `json:"subtotal"`
	// Tổng phí ship của tất cả các shop (chưa trừ voucher ship)
	TotalShippingFee string `json:"total_shipping_fee"`
	// Tổng tất cả các khoản giảm giá (từ voucher shop, sàn và ship)
	TotalDiscount string `json:"total_discount"`
	// Mã voucher của sàn áp dụng cho tiền hàng
	SiteOrderVoucherCode sql.NullString `json:"site_order_voucher_code"`
	// Số tiền giảm từ voucher tiền hàng của sàn
	SiteOrderVoucherDiscount sql.NullString `json:"site_order_voucher_discount"`
	// Mã voucher của sàn áp dụng cho phí ship
	SiteShippingVoucherCode sql.NullString `json:"site_shipping_voucher_code"`
	// Số tiền giảm từ voucher phí ship của sàn
	SiteShippingVoucherDiscount sql.NullString `json:"site_shipping_voucher_discount"`
	// Bản ghi nhanh (snapshot) địa chỉ giao hàng dạng JSON
	ShippingAddressSnapshot json.RawMessage `json:"shipping_address_snapshot"`
	// Bản ghi nhanh (snapshot) phương thức thanh toán dạng JSON
	PaymentMethodSnapshot json.RawMessage `json:"payment_method_snapshot"`
	// Ghi chú của khách hàng cho toàn bộ đơn hàng
	Note sql.NullString `json:"note"`
	// Thời gian tạo đơn hàng
	CreatedAt time.Time `json:"created_at"`
	// Thời gian cập nhật lần cuối
	UpdatedAt time.Time `json:"updated_at"`
}

// Bảng chứa các đơn hàng chi tiết của từng shop, là đơn vị vận hành chính
type ShopOrders struct {
	// UUID, Khóa chính của đơn hàng shop
	ID string `json:"id"`
	// Mã đơn hàng duy nhất, thân thiện với shop (ví dụ: SHOP-ABC-123)
	ShopOrderCode string `json:"shop_order_code"`
	// Khóa ngoại, liên kết tới đơn hàng tổng trong bảng orders
	OrderID string `json:"order_id"`
	// UUID của shop/nhà bán hàng
	ShopID string `json:"shop_id"`
	// Trạng thái xử lý CHI TIẾT của gói hàng này. Đây là "Source of Truth"
	Status ShopOrdersStatus `json:"status"`
	// Tổng tiền hàng của các sản phẩm thuộc shop này
	Subtotal string `json:"subtotal"`
	// Tổng giảm giá của shop này (từ voucher shop + khuyến mãi sản phẩm)
	TotalDiscount string `json:"total_discount"`
	// Tổng tiền cuối cùng của shop này (subtotal + shipping_fee - total_discount)
	TotalAmount string `json:"total_amount"`
	// Mã voucher của shop đã áp dụng
	ShopVoucherCode sql.NullString `json:"shop_voucher_code"`
	// Số tiền giảm từ voucher của shop
	ShopVoucherDiscount sql.NullString `json:"shop_voucher_discount"`
	// Tổng phí ship của  shop (chưa trừ voucher ship)
	ShippingFee string `json:"shipping_fee"`
	// Tên đơn vị vận chuyển
	ShippingMethod sql.NullString `json:"shipping_method"`
	// Mã vận đơn của đơn vị vận chuyển
	TrackingCode sql.NullString `json:"tracking_code"`
	// Lý do hủy đơn hàng (nếu có)
	CancellationReason sql.NullString `json:"cancellation_reason"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	// Thời điểm được xác nhận đã thanh toán
	PaidAt sql.NullTime `json:"paid_at"`
	// Thời điểm shop bắt đầu xử lý hàng
	ProcessingAt sql.NullTime `json:"processing_at"`
	// Thời điểm shop bàn giao cho ĐVVC
	ShippedAt sql.NullTime `json:"shipped_at"`
	// Thời điểm giao hàng thành công
	CompletedAt sql.NullTime `json:"completed_at"`
	// Thời điểm đơn hàng bị hủy
	CancelledAt sql.NullTime `json:"cancelled_at"`
}

// Lưu trữ các voucher được gán riêng cho người dùng
type UserVouchers struct {
	ID uint64 `json:"id"`
	// UUID của người dùng
	UserID string `json:"user_id"`
	// Khóa ngoại tới bảng vouchers
	VoucherID string `json:"voucher_id"`
	// Trạng thái voucher trong ví
	Status UserVouchersStatus `json:"status"`
}

// Lịch sử sử dụng voucher để đối soát
type VoucherUsageHistory struct {
	ID uint64 `json:"id"`
	// Khóa ngoại tới bảng vouchers
	VoucherID string `json:"voucher_id"`
	// Người dùng đã sử dụng
	UserID string `json:"user_id"`
	// Số tiền thực tế đã giảm
	DiscountAmount string    `json:"discount_amount"`
	UsedAt         time.Time `json:"used_at"`
}

// Bảng chính, định nghĩa voucher và các điều kiện đơn giản
type Vouchers struct {
	// UUID, Khóa chính
	ID string `json:"id"`
	// Tên hiển thị (Voucher 50k, Freeship)
	Name string `json:"name"`
	// Mã voucher (SALE50K). Phải là UNIQUE
	VoucherCode string `json:"voucher_code"`
	// PLATFORM (Sàn) hay SHOP (Nhà bán hàng)
	OwnerType VouchersOwnerType `json:"owner_type"`
	// ID của Shop (nếu owner_type=SHOP) hoặc UUID cố định của Sàn
	OwnerID string `json:"owner_id"`
	// Giảm theo % hay Số tiền cố định
	DiscountType VouchersDiscountType `json:"discount_type"`
	// Giá trị giảm (VD: 5 cho 5%, hoặc 50000 cho 50k)
	DiscountValue string `json:"discount_value"`
	// Số tiền giảm TỐI ĐA (cho discount_type=PERCENTAGE)
	MaxDiscountAmount sql.NullString `json:"max_discount_amount"`
	// Giảm trên: Tổng đơn hàng hay Phí vận chuyển
	AppliesToType VouchersAppliesToType `json:"applies_to_type"`
	// ĐIỀU KIỆN: Giá trị đơn hàng tối thiểu để áp dụng
	MinPurchaseAmount string `json:"min_purchase_amount"`
	// PUBLIC (công khai) hay ASSIGNED (chỉ định riêng)
	AudienceType VouchersAudienceType `json:"audience_type"`
	// Thời gian bắt đầu hiệu lực
	StartDate time.Time `json:"start_date"`
	// Thời gian kết thúc hiệu lực
	EndDate time.Time `json:"end_date"`
	// Tổng số lượt có thể sử dụng (giới hạn toàn hệ thống)
	TotalQuantity int32 `json:"total_quantity"`
	// Số lượt đã sử dụng (dùng để check race condition)
	UsedQuantity int32 `json:"used_quantity"`
	// Số lượt tối đa mỗi user được dùng
	MaxUsagePerUser int32 `json:"max_usage_per_user"`
	// Bật/Tắt voucher
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
