// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const createOrder = `-- name: CreateOrder :exec

INSERT INTO orders (
  id, order_code, user_id, grand_total, subtotal, total_shipping_fee, total_discount,
  site_order_voucher_code, site_order_voucher_discount, site_shipping_voucher_code, site_shipping_voucher_discount,
  shipping_address_snapshot, payment_method_snapshot, note
) VALUES (
  ?, ?, ?, ?, ?, ?, ?,  ?, ?, ?, ?, ?, ?, ?
)
`

type CreateOrderParams struct {
	ID                          string          `json:"id"`
	OrderCode                   string          `json:"order_code"`
	UserID                      string          `json:"user_id"`
	GrandTotal                  string          `json:"grand_total"`
	Subtotal                    string          `json:"subtotal"`
	TotalShippingFee            string          `json:"total_shipping_fee"`
	TotalDiscount               string          `json:"total_discount"`
	SiteOrderVoucherCode        sql.NullString  `json:"site_order_voucher_code"`
	SiteOrderVoucherDiscount    sql.NullString  `json:"site_order_voucher_discount"`
	SiteShippingVoucherCode     sql.NullString  `json:"site_shipping_voucher_code"`
	SiteShippingVoucherDiscount sql.NullString  `json:"site_shipping_voucher_discount"`
	ShippingAddressSnapshot     json.RawMessage `json:"shipping_address_snapshot"`
	PaymentMethodSnapshot       json.RawMessage `json:"payment_method_snapshot"`
	Note                        sql.NullString  `json:"note"`
}

// =================================================================
// Queries for `orders` table
// =================================================================
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) error {
	_, err := q.db.ExecContext(ctx, createOrder,
		arg.ID,
		arg.OrderCode,
		arg.UserID,
		arg.GrandTotal,
		arg.Subtotal,
		arg.TotalShippingFee,
		arg.TotalDiscount,
		arg.SiteOrderVoucherCode,
		arg.SiteOrderVoucherDiscount,
		arg.SiteShippingVoucherCode,
		arg.SiteShippingVoucherDiscount,
		arg.ShippingAddressSnapshot,
		arg.PaymentMethodSnapshot,
		arg.Note,
	)
	return err
}

const getOrderByCode = `-- name: GetOrderByCode :one
SELECT id, order_code, user_id, grand_total, subtotal, total_shipping_fee, total_discount, site_order_voucher_code, site_order_voucher_discount, site_shipping_voucher_code, site_shipping_voucher_discount, shipping_address_snapshot, payment_method_snapshot, note, created_at, updated_at FROM orders
WHERE order_code = ? LIMIT 1
`

func (q *Queries) GetOrderByCode(ctx context.Context, orderCode string) (Orders, error) {
	row := q.db.QueryRowContext(ctx, getOrderByCode, orderCode)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderCode,
		&i.UserID,
		&i.GrandTotal,
		&i.Subtotal,
		&i.TotalShippingFee,
		&i.TotalDiscount,
		&i.SiteOrderVoucherCode,
		&i.SiteOrderVoucherDiscount,
		&i.SiteShippingVoucherCode,
		&i.SiteShippingVoucherDiscount,
		&i.ShippingAddressSnapshot,
		&i.PaymentMethodSnapshot,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_code, user_id, grand_total, subtotal, total_shipping_fee, total_discount, site_order_voucher_code, site_order_voucher_discount, site_shipping_voucher_code, site_shipping_voucher_discount, shipping_address_snapshot, payment_method_snapshot, note, created_at, updated_at FROM orders
WHERE id = ? LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id string) (Orders, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderCode,
		&i.UserID,
		&i.GrandTotal,
		&i.Subtotal,
		&i.TotalShippingFee,
		&i.TotalDiscount,
		&i.SiteOrderVoucherCode,
		&i.SiteOrderVoucherDiscount,
		&i.SiteShippingVoucherCode,
		&i.SiteShippingVoucherDiscount,
		&i.ShippingAddressSnapshot,
		&i.PaymentMethodSnapshot,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, order_code, user_id, grand_total, subtotal, total_shipping_fee, total_discount, site_order_voucher_code, site_order_voucher_discount, site_shipping_voucher_code, site_shipping_voucher_discount, shipping_address_snapshot, payment_method_snapshot, note, created_at, updated_at FROM orders
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID string) ([]Orders, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.OrderCode,
			&i.UserID,
			&i.GrandTotal,
			&i.Subtotal,
			&i.TotalShippingFee,
			&i.TotalDiscount,
			&i.SiteOrderVoucherCode,
			&i.SiteOrderVoucherDiscount,
			&i.SiteShippingVoucherCode,
			&i.SiteShippingVoucherDiscount,
			&i.ShippingAddressSnapshot,
			&i.PaymentMethodSnapshot,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserIDPaged = `-- name: ListOrdersByUserIDPaged :many
SELECT id, order_code, user_id, grand_total, subtotal, total_shipping_fee, total_discount, site_order_voucher_code, site_order_voucher_discount, site_shipping_voucher_code, site_shipping_voucher_discount, shipping_address_snapshot, payment_method_snapshot, note, created_at, updated_at FROM orders
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListOrdersByUserIDPagedParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListOrdersByUserIDPaged(ctx context.Context, arg ListOrdersByUserIDPagedParams) ([]Orders, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserIDPaged, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.OrderCode,
			&i.UserID,
			&i.GrandTotal,
			&i.Subtotal,
			&i.TotalShippingFee,
			&i.TotalDiscount,
			&i.SiteOrderVoucherCode,
			&i.SiteOrderVoucherDiscount,
			&i.SiteShippingVoucherCode,
			&i.SiteShippingVoucherDiscount,
			&i.ShippingAddressSnapshot,
			&i.PaymentMethodSnapshot,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderShippingAddress = `-- name: UpdateOrderShippingAddress :exec
UPDATE orders
SET
  shipping_address_snapshot = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateOrderShippingAddressParams struct {
	ShippingAddressSnapshot json.RawMessage `json:"shipping_address_snapshot"`
	ID                      string          `json:"id"`
}

func (q *Queries) UpdateOrderShippingAddress(ctx context.Context, arg UpdateOrderShippingAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderShippingAddress, arg.ShippingAddressSnapshot, arg.ID)
	return err
}

const updateOrderTotals = `-- name: UpdateOrderTotals :exec
UPDATE orders
SET
  grand_total = ?,
  subtotal = ?,
  total_shipping_fee = ?,
  total_discount = ?,
  updated_at = NOW()
WHERE id = ?
`

type UpdateOrderTotalsParams struct {
	GrandTotal       string `json:"grand_total"`
	Subtotal         string `json:"subtotal"`
	TotalShippingFee string `json:"total_shipping_fee"`
	TotalDiscount    string `json:"total_discount"`
	ID               string `json:"id"`
}

func (q *Queries) UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderTotals,
		arg.GrandTotal,
		arg.Subtotal,
		arg.TotalShippingFee,
		arg.TotalDiscount,
		arg.ID,
	)
	return err
}
