// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createOrderItem = `-- name: CreateOrderItem :exec

INSERT INTO order_items (
  id, shop_order_id, product_id, sku_id, quantity, original_unit_price, final_unit_price, total_price,
  promotions_snapshot, product_name_snapshot, product_image_snapshot, sku_attributes_snapshot
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateOrderItemParams struct {
	ID                    string         `json:"id"`
	ShopOrderID           string         `json:"shop_order_id"`
	ProductID             string         `json:"product_id"`
	SkuID                 string         `json:"sku_id"`
	Quantity              uint32         `json:"quantity"`
	OriginalUnitPrice     string         `json:"original_unit_price"`
	FinalUnitPrice        string         `json:"final_unit_price"`
	TotalPrice            string         `json:"total_price"`
	PromotionsSnapshot    sql.NullString `json:"promotions_snapshot"`
	ProductNameSnapshot   string         `json:"product_name_snapshot"`
	ProductImageSnapshot  sql.NullString `json:"product_image_snapshot"`
	SkuAttributesSnapshot sql.NullString `json:"sku_attributes_snapshot"`
}

// =================================================================
// Queries for `order_items` table
// =================================================================
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, createOrderItem,
		arg.ID,
		arg.ShopOrderID,
		arg.ProductID,
		arg.SkuID,
		arg.Quantity,
		arg.OriginalUnitPrice,
		arg.FinalUnitPrice,
		arg.TotalPrice,
		arg.PromotionsSnapshot,
		arg.ProductNameSnapshot,
		arg.ProductImageSnapshot,
		arg.SkuAttributesSnapshot,
	)
	return err
}

const getOrderItemsByShopOrderIDs = `-- name: GetOrderItemsByShopOrderIDs :many



SELECT shop_order_id, sku_id, quantity
FROM order_items
WHERE shop_order_id IN (/*SLICE:shop_order_ids*/?)
`

type GetOrderItemsByShopOrderIDsRow struct {
	ShopOrderID string `json:"shop_order_id"`
	SkuID       string `json:"sku_id"`
	Quantity    uint32 `json:"quantity"`
}

// -- =================================================================
// -- Queries for `order_status_history` table
// -- =================================================================
// -- name: CreateOrderStatusHistory :exec
// INSERT INTO order_status_history (
//
//	shop_order_id, status, notes, created_by
//
// ) VALUES (
//
//	?, ?, ?, ?
//
// );
// -- name: ListOrderStatusHistoryByShopOrderID :many
// SELECT * FROM order_status_history
// WHERE shop_order_id = ?
// ORDER BY created_at ASC;
// Lấy tất cả items thuộc các shop_orders (để gửi event 'order_cancelled' cho Product Service)
func (q *Queries) GetOrderItemsByShopOrderIDs(ctx context.Context, shopOrderIds []string) ([]GetOrderItemsByShopOrderIDsRow, error) {
	query := getOrderItemsByShopOrderIDs
	var queryParams []interface{}
	if len(shopOrderIds) > 0 {
		for _, v := range shopOrderIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:shop_order_ids*/?", strings.Repeat(",?", len(shopOrderIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:shop_order_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByShopOrderIDsRow
	for rows.Next() {
		var i GetOrderItemsByShopOrderIDsRow
		if err := rows.Scan(&i.ShopOrderID, &i.SkuID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTotalSold = `-- name: GetProductTotalSold :many





SELECT
  oi.product_id,
CAST(COALESCE(SUM(oi.quantity), 0) AS SIGNED) AS total_sold
FROM
  order_items AS oi
JOIN
  shop_orders AS so ON oi.shop_order_id = so.id
WHERE
  oi.product_id IN (/*SLICE:product_ids*/?)
  AND so.status IN ('PROCESSING', 'SHIPPED', 'COMPLETED')
GROUP BY
  oi.product_id
`

type GetProductTotalSoldRow struct {
	ProductID string `json:"product_id"`
	TotalSold int64  `json:"total_sold"`
}

// lấy tổng số lượng đã bán của các product_ids trong các đơn hàng có trạng thái 'PROCESSING', 'SHIPPED', 'COMPLETED'(đang dùng cho product_service)
func (q *Queries) GetProductTotalSold(ctx context.Context, productIds []string) ([]GetProductTotalSoldRow, error) {
	query := getProductTotalSold
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductTotalSoldRow
	for rows.Next() {
		var i GetProductTotalSoldRow
		if err := rows.Scan(&i.ProductID, &i.TotalSold); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByShopOrderID = `-- name: ListOrderItemsByShopOrderID :many
SELECT id, shop_order_id, product_id, sku_id, quantity, original_unit_price, final_unit_price, total_price, promotions_snapshot, product_name_snapshot, product_image_snapshot, sku_attributes_snapshot FROM order_items
WHERE shop_order_id = ?
`

func (q *Queries) ListOrderItemsByShopOrderID(ctx context.Context, shopOrderID string) ([]OrderItems, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByShopOrderID, shopOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItems
	for rows.Next() {
		var i OrderItems
		if err := rows.Scan(
			&i.ID,
			&i.ShopOrderID,
			&i.ProductID,
			&i.SkuID,
			&i.Quantity,
			&i.OriginalUnitPrice,
			&i.FinalUnitPrice,
			&i.TotalPrice,
			&i.PromotionsSnapshot,
			&i.ProductNameSnapshot,
			&i.ProductImageSnapshot,
			&i.SkuAttributesSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
