// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_comment.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const checkBulkOrderItemsReviewed = `-- name: CheckBulkOrderItemsReviewed :many
SELECT order_item_id FROM product_comment
WHERE order_item_id IN (/*SLICE:order_item_ids*/?)
`

// Kiểm tra danh sách order_item_id đã được review chưa
// Chỉ trả về những order_item_id đã có bình luận
func (q *Queries) CheckBulkOrderItemsReviewed(ctx context.Context, orderItemIds []string) ([]string, error) {
	query := checkBulkOrderItemsReviewed
	var queryParams []interface{}
	if len(orderItemIds) > 0 {
		for _, v := range orderItemIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:order_item_ids*/?", strings.Repeat(",?", len(orderItemIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:order_item_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var order_item_id string
		if err := rows.Scan(&order_item_id); err != nil {
			return nil, err
		}
		items = append(items, order_item_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countReviewLikes = `-- name: CountReviewLikes :one
SELECT COUNT(*) FROM review_likes
WHERE review_id = ?
`

// Đếm số lượt "Hữu ích" của một review
func (q *Queries) CountReviewLikes(ctx context.Context, reviewID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReviewLikes, reviewID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :exec
INSERT INTO product_comment (
  comment_id,
  order_item_id,
  product_id,
  sku_id,
  user_id,
  sku_name_snapshot,
  rating,
  title,
  content,
  media,
  parent_id
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateCommentParams struct {
	CommentID       string         `json:"comment_id"`
	OrderItemID     string         `json:"order_item_id"`
	ProductID       string         `json:"product_id"`
	SkuID           string         `json:"sku_id"`
	UserID          string         `json:"user_id"`
	SkuNameSnapshot sql.NullString `json:"sku_name_snapshot"`
	Rating          int8           `json:"rating"`
	Title           sql.NullString `json:"title"`
	Content         sql.NullString `json:"content"`
	Media           sql.NullString `json:"media"`
	ParentID        sql.NullString `json:"parent_id"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) error {
	_, err := q.db.ExecContext(ctx, createComment,
		arg.CommentID,
		arg.OrderItemID,
		arg.ProductID,
		arg.SkuID,
		arg.UserID,
		arg.SkuNameSnapshot,
		arg.Rating,
		arg.Title,
		arg.Content,
		arg.Media,
		arg.ParentID,
	)
	return err
}

const createReviewLike = `-- name: CreateReviewLike :exec
INSERT INTO review_likes (
  review_id, user_id
) VALUES (
  ?, ?
)
`

type CreateReviewLikeParams struct {
	ReviewID string `json:"review_id"`
	UserID   string `json:"user_id"`
}

// Thêm một lượt "Hữu ích" cho review
func (q *Queries) CreateReviewLike(ctx context.Context, arg CreateReviewLikeParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLike, arg.ReviewID, arg.UserID)
	return err
}

const deleteReviewLike = `-- name: DeleteReviewLike :exec
DELETE FROM review_likes
WHERE review_id = ? AND user_id = ?
`

type DeleteReviewLikeParams struct {
	ReviewID string `json:"review_id"`
	UserID   string `json:"user_id"`
}

// Bỏ lượt "Hữu ích"
func (q *Queries) DeleteReviewLike(ctx context.Context, arg DeleteReviewLikeParams) error {
	_, err := q.db.ExecContext(ctx, deleteReviewLike, arg.ReviewID, arg.UserID)
	return err
}

const getBulkProductRatingStats = `-- name: GetBulkProductRatingStats :many
SELECT
  product_id,
  COUNT(*) AS total_reviews,
  AVG(rating) AS average_rating
FROM product_comment
WHERE product_id IN (/*SLICE:product_ids*/?) AND parent_id IS NULL
GROUP BY product_id
`

type GetBulkProductRatingStatsRow struct {
	ProductID     string      `json:"product_id"`
	TotalReviews  int64       `json:"total_reviews"`
	AverageRating interface{} `json:"average_rating"`
}

// Lấy điểm đánh giá trung bình và tổng số lượt đánh giá cho nhiều sản phẩm
// Chỉ tính các bình luận gốc (parent_id IS NULL).
func (q *Queries) GetBulkProductRatingStats(ctx context.Context, productIds []string) ([]GetBulkProductRatingStatsRow, error) {
	query := getBulkProductRatingStats
	var queryParams []interface{}
	if len(productIds) > 0 {
		for _, v := range productIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:product_ids*/?", strings.Repeat(",?", len(productIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:product_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkProductRatingStatsRow
	for rows.Next() {
		var i GetBulkProductRatingStatsRow
		if err := rows.Scan(&i.ProductID, &i.TotalReviews, &i.AverageRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentByOrderItemID = `-- name: GetCommentByOrderItemID :one
SELECT comment_id, order_item_id, product_id, sku_id, user_id, sku_name_snapshot, rating, title, content, media, parent_id, created_at, updated_at FROM product_comment
WHERE order_item_id = ?
`

// Dùng để check xem order_item_id này đã được review hay chưa.
func (q *Queries) GetCommentByOrderItemID(ctx context.Context, orderItemID string) (ProductComment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByOrderItemID, orderItemID)
	var i ProductComment
	err := row.Scan(
		&i.CommentID,
		&i.OrderItemID,
		&i.ProductID,
		&i.SkuID,
		&i.UserID,
		&i.SkuNameSnapshot,
		&i.Rating,
		&i.Title,
		&i.Content,
		&i.Media,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductRatingStats = `-- name: GetProductRatingStats :one
SELECT
  COUNT(*) AS total_reviews,
  AVG(rating) AS average_rating
FROM product_comment
WHERE product_id = ? AND parent_id IS NULL
`

type GetProductRatingStatsRow struct {
	TotalReviews  int64       `json:"total_reviews"`
	AverageRating interface{} `json:"average_rating"`
}

// Lấy điểm đánh giá trung bình và tổng số lượt đánh giá cho một sản phẩm.
// Chỉ tính các bình luận gốc (parent_id IS NULL).
func (q *Queries) GetProductRatingStats(ctx context.Context, productID string) (GetProductRatingStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getProductRatingStats, productID)
	var i GetProductRatingStatsRow
	err := row.Scan(&i.TotalReviews, &i.AverageRating)
	return i, err
}

const getRepliesByCommentID = `-- name: GetRepliesByCommentID :many
SELECT comment_id, order_item_id, product_id, sku_id, user_id, sku_name_snapshot, rating, title, content, media, parent_id, created_at, updated_at FROM product_comment
WHERE parent_id = ?
ORDER BY created_at ASC
`

// Lấy danh sách các bình luận trả lời (replies) cho một comment gốc
func (q *Queries) GetRepliesByCommentID(ctx context.Context, parentID sql.NullString) ([]ProductComment, error) {
	rows, err := q.db.QueryContext(ctx, getRepliesByCommentID, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductComment
	for rows.Next() {
		var i ProductComment
		if err := rows.Scan(
			&i.CommentID,
			&i.OrderItemID,
			&i.ProductID,
			&i.SkuID,
			&i.UserID,
			&i.SkuNameSnapshot,
			&i.Rating,
			&i.Title,
			&i.Content,
			&i.Media,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByProduct = `-- name: ListCommentsByProduct :many
SELECT comment_id, order_item_id, product_id, sku_id, user_id, sku_name_snapshot, rating, title, content, media, parent_id, created_at, updated_at FROM product_comment
WHERE product_id = ? 
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListCommentsByProductParams struct {
	ProductID string `json:"product_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

// Lấy danh sách bình luận (gốc, không phải trả lời) cho một sản phẩm, hỗ trợ phân trang.
func (q *Queries) ListCommentsByProduct(ctx context.Context, arg ListCommentsByProductParams) ([]ProductComment, error) {
	rows, err := q.db.QueryContext(ctx, listCommentsByProduct, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductComment
	for rows.Next() {
		var i ProductComment
		if err := rows.Scan(
			&i.CommentID,
			&i.OrderItemID,
			&i.ProductID,
			&i.SkuID,
			&i.UserID,
			&i.SkuNameSnapshot,
			&i.Rating,
			&i.Title,
			&i.Content,
			&i.Media,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
