// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Cập nhật trạng thái một loạt shop_orders thành CANCELLED
	CancelShopOrdersByIDs(ctx context.Context, arg CancelShopOrdersByIDsParams) error
	// Đếm số lần user đã sử dụng 1 voucher (cho check max_usage_per_user)
	CountVoucherUsageByUser(ctx context.Context, arg CountVoucherUsageByUserParams) (int64, error)
	// =================================================================
	// Queries for `orders` table
	// =================================================================
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	// =================================================================
	// Queries for `order_items` table
	// =================================================================
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) error
	// =================================================================
	// Queries for `shop_orders` table
	// =================================================================
	CreateShopOrder(ctx context.Context, arg CreateShopOrderParams) error
	CreateVoucher(ctx context.Context, arg CreateVoucherParams) error
	// Ghi lại lịch sử sử dụng voucher
	CreateVoucherUsageHistory(ctx context.Context, arg CreateVoucherUsageHistoryParams) error
	// Giảm số lượng đã dùng (khi hủy đơn)
	DecrementVoucherUsage(ctx context.Context, id string) (int64, error)
	// Xóa 1 dòng lịch sử cụ thể (khi hủy đơn)
	DeleteVoucherUsageHistory(ctx context.Context, id uint64) (int64, error)
	// Lấy danh sách voucher ĐƯỢC GÁN RIÊNG (cho 1 user)
	// Chỉ lấy voucher còn hiệu lực, còn trạng thái AVAILABLE
	GetAssignedVouchersByUser(ctx context.Context, userID string) ([]Vouchers, error)
	// Lấy danh sách voucher ĐƯỢC GÁN RIÊNG với bộ lọc
	GetAssignedVouchersByUserWithFilter(ctx context.Context, arg GetAssignedVouchersByUserWithFilterParams) ([]Vouchers, error)
	GetOrderByCode(ctx context.Context, orderCode string) (Orders, error)
	GetOrderByID(ctx context.Context, id string) (Orders, error)
	// -- =================================================================
	// -- Queries for `order_status_history` table
	// -- =================================================================
	// -- name: CreateOrderStatusHistory :exec
	// INSERT INTO order_status_history (
	//   shop_order_id, status, notes, created_by
	// ) VALUES (
	//   ?, ?, ?, ?
	// );
	// -- name: ListOrderStatusHistoryByShopOrderID :many
	// SELECT * FROM order_status_history
	// WHERE shop_order_id = ?
	// ORDER BY created_at ASC;
	// Lấy tất cả items thuộc các shop_orders (để gửi event 'order_cancelled' cho Product Service)
	GetOrderItemsByShopOrderIDs(ctx context.Context, shopOrderIds []string) ([]GetOrderItemsByShopOrderIDsRow, error)
	// Lấy danh sách voucher CÔNG KHAI (cho toàn bộ người dùng)
	// Chỉ lấy voucher còn hiệu lực và còn số lượng
	GetPublicVouchers(ctx context.Context) ([]Vouchers, error)
	// Lấy danh sách voucher CÔNG KHAI với bộ lọc
	GetPublicVouchersWithFilter(ctx context.Context, arg GetPublicVouchersWithFilterParams) ([]Vouchers, error)
	GetShopOrderByID(ctx context.Context, id string) (ShopOrders, error)
	// Lấy trạng thái voucher trong ví của user (cho check voucher ĐƯỢC GÁN)
	GetUserVoucherStatus(ctx context.Context, arg GetUserVoucherStatusParams) (UserVouchers, error)
	// Lấy voucher bằng ID (không check điều kiện)
	GetVoucherByID(ctx context.Context, id string) (Vouchers, error)
	// Lấy thông tin voucher bằng ID để kiểm tra (THÊM MỚI)
	// Chỉ trả về voucher nếu nó CƠ BẢN hợp lệ (còn hạn, còn lượt)
	GetVoucherByIDForValidation(ctx context.Context, id string) (Vouchers, error)
	// =============================================
	// CÁC HÀM LẤY DỮ LIỆU ĐỂ "CHECK" TRONG CODE LOGIC
	// =============================================
	// Lấy thông tin voucher bằng MÃ (code) để kiểm tra
	// Chỉ trả về voucher nếu nó CƠ BẢN hợp lệ (còn hạn, còn lượt)
	GetVoucherForValidation(ctx context.Context, voucherCode string) (Vouchers, error)
	// Lấy 1 dòng lịch sử sử dụng cụ thể
	GetVoucherUsageHistory(ctx context.Context, arg GetVoucherUsageHistoryParams) (VoucherUsageHistory, error)
	// =============================================
	// CÁC HÀM "COMMAND" KHI TẠO ĐƠN HÀNG
	// =============================================
	// Tăng số lượng đã dùng. Dùng :execrows để check race condition
	// (Logic code phải kiểm tra RowsAffected() == 1)
	IncrementVoucherUsage(ctx context.Context, id string) (int64, error)
	ListOrderItemsByShopOrderID(ctx context.Context, shopOrderID string) ([]OrderItems, error)
	ListOrdersByUserID(ctx context.Context, userID string) ([]Orders, error)
	ListOrdersByUserIDPaged(ctx context.Context, arg ListOrdersByUserIDPagedParams) ([]Orders, error)
	ListShopOrdersByOrderID(ctx context.Context, arg ListShopOrdersByOrderIDParams) ([]ShopOrders, error)
	ListShopOrdersByShopIDPaged(ctx context.Context, arg ListShopOrdersByShopIDPagedParams) ([]ShopOrders, error)
	// -- name: ListShopOrdersByStatus :many
	// SELECT shop_orders.* FROM shop_orders
	// JOIN orders ON shop_orders.order_id = orders.id
	// WHERE
	//     shop_orders.status = ? AND orders.user_id = ?
	// ORDER BY
	//     shop_orders.created_at DESC
	// LIMIT ? OFFSET ?;
	ListShopOrdersByStatus(ctx context.Context, arg ListShopOrdersByStatusParams) ([]ShopOrders, error)
	//
	ListShopOrdersByStatusCount(ctx context.Context, arg ListShopOrdersByStatusCountParams) (int64, error)
	// Xóa bằng ID của bảng history
	// Reset trạng thái ví voucher (từ USED về AVAILABLE)
	ResetUserVoucherStatus(ctx context.Context, arg ResetUserVoucherStatusParams) (int64, error)
	SearchShopOrders(ctx context.Context, arg SearchShopOrdersParams) ([]ShopOrders, error)
	SearchShopOrdersCount(ctx context.Context, arg SearchShopOrdersCountParams) (int64, error)
	// Cập nhật trạng thái voucher trong ví user (từ AVAILABLE -> USED)
	// (Logic code nên kiểm tra RowsAffected() == 1)
	SetUserVoucherStatus(ctx context.Context, arg SetUserVoucherStatusParams) (int64, error)
	UpdateOrderShippingAddress(ctx context.Context, arg UpdateOrderShippingAddressParams) error
	UpdateOrderTotals(ctx context.Context, arg UpdateOrderTotalsParams) error
	UpdateShopOrderGeneralInfo(ctx context.Context, arg UpdateShopOrderGeneralInfoParams) error
	UpdateShopOrderStatusToCancelled(ctx context.Context, arg UpdateShopOrderStatusToCancelledParams) error
	UpdateShopOrderStatusToCompleted(ctx context.Context, id string) error
	UpdateShopOrderStatusToProcessing(ctx context.Context, id string) error
	UpdateShopOrderStatusToRefunded(ctx context.Context, id string) error
	UpdateShopOrderStatusToShipped(ctx context.Context, arg UpdateShopOrderStatusToShippedParams) error
	// Cập nhật từng phần (Partial Update)
	UpdateVoucher(ctx context.Context, arg UpdateVoucherParams) error
}

var _ Querier = (*Queries)(nil)
