// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: summarize.sql

package db

import (
	"context"
	"database/sql"
)

const checkReviewPermission = `-- name: CheckReviewPermission :one
SELECT
    oi.product_id,
    oi.sku_id,
    oi.sku_attributes_snapshot
FROM 
    shop_orders so
JOIN 
    orders o ON so.order_id = o.id
JOIN 
    order_items oi ON oi.shop_order_id = so.id
WHERE 
    oi.id = ?           -- (sqlc.arg: order_item_id)
    AND o.user_id = ?   -- (sqlc.arg: user_id)
    AND so.status = 'COMPLETED'
LIMIT 1
`

type CheckReviewPermissionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

type CheckReviewPermissionRow struct {
	ProductID             string         `json:"product_id"`
	SkuID                 string         `json:"sku_id"`
	SkuAttributesSnapshot sql.NullString `json:"sku_attributes_snapshot"`
}

// Xác thực quyền review:
// 1. order_item_id có tồn tại (JOIN order_items)
// 2. order_item_id đó có thuộc về user_id này (WHERE o.user_id = ?)
// 3. Đơn hàng shop (shop_order) chứa item đó PHẢI ở trạng thái 'COMPLETED' (WHERE so.status = 'COMPLETED')
func (q *Queries) CheckReviewPermission(ctx context.Context, arg CheckReviewPermissionParams) (CheckReviewPermissionRow, error) {
	row := q.db.QueryRowContext(ctx, checkReviewPermission, arg.ID, arg.UserID)
	var i CheckReviewPermissionRow
	err := row.Scan(&i.ProductID, &i.SkuID, &i.SkuAttributesSnapshot)
	return i, err
}
