// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voucher_use.sql

package db

import (
	"context"
)

const createVoucherUser = `-- name: CreateVoucherUser :exec
INSERT INTO user_vouchers (
    user_id,
    voucher_id,
    ` + "`" + `status` + "`" + `
) VALUES (
    ?, ?, ?
)
`

type CreateVoucherUserParams struct {
	UserID    string             `json:"user_id"`
	VoucherID string             `json:"voucher_id"`
	Status    UserVouchersStatus `json:"status"`
}

// tạo ra voucher cho riêng người dùng
func (q *Queries) CreateVoucherUser(ctx context.Context, arg CreateVoucherUserParams) error {
	_, err := q.db.ExecContext(ctx, createVoucherUser, arg.UserID, arg.VoucherID, arg.Status)
	return err
}
