# variables:
#     PROJECT_NAME: ORDER_service
#     DOCKER_IMAGE: ${REGISTRY_USER}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
#     DOCKER_CONTAINER: ${CI_PROJECT_NAME}/${PROJECT_NAME}
#     HOST_PORT: "9001"
#     CONTAINER_PORT: "9001"
# stages:
#     - buildandpush
#     - deploy
#     - showlog

# buildandpush:
#     stage: buildandpush
#     variables:
#         GIT_STRATEGY: clone
#     before_script:
#         - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
#     script:
#         - docker build -t $DOCKER_IMAGE .
#         - docker push $DOCKER_IMAGE
#     tags:
#         - server-dev
#     only:
#         - tags

# deploy:
#     stage: deploy
#     variables:
#         GIT_STRATEGY: none
#     before_script:
#         - docker login  -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
#     script:
#         - docker pull $DOCKER_IMAGE
#         - docker rm -f $DOCKER_CONTAINER
#         - docker run --name $DOCKER_CONTAINER -d -p $HOST_PORT:$CONTAINER_PORT $DOCKER_IMAGE
#     tags:
#         - server-dev
#     only:
#         - tags

# showlog:
#     stage: showlog
#     variables:
#         GIT_STRATEGY: none
#     script:
#         - sleep 20
#         - docker logs $DOCKER_CONTAINER
#     tags:
#         - server-dev
#     only:
#         - tags
variables:
  ORDER_NAME: "api-order-service" 
  ORDER_IMAGE: ${REGISTRY_USER}/${ORDER_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  ORDER_CONTAINER: ${CI_PROJECT_NAME}___${ORDER_NAME}   
  ORDER_HOST_PORT: "9002"
  ORDER_CONTAINER_PORT: "9002"
  SERVICE_PATH: "api_system/ecom_order_service"

build_order:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - echo "Building order Service..."
    - cd $SERVICE_PATH 
    - docker build -t $ORDER_IMAGE .
    - docker push $ORDER_IMAGE
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_order_service/**/*

deploy_order:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull $ORDER_IMAGE
    - docker rm -f $ORDER_CONTAINER || true
    - docker run --name $ORDER_CONTAINER \
      --env-file $ENV_FILE_ORDER \
      --restart unless-stopped \
      -d -p $ORDER_HOST_PORT:$ORDER_CONTAINER_PORT \
      $ORDER_IMAGE
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_order_service/**/*

showlog_order:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 10
    - docker logs $ORDER_CONTAINER
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_order_service/**/*