import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl"
import { routing } from '@/i18n/routing';
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { ThemeProvider } from "../../components/theme-provider";
import Layout from "@/resources/layout/ContainerLayout";
import TanstackQueryProvider from "@/assets/middleware/reactQueryProvider";
// const geistSans = localFont({
//   src: "../fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "../fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }
  const messages = await getMessages()
  return (
    <NextIntlClientProvider messages={messages}>
      <html lang={locale}>
        <head>
          {/* Google Fonts - Playfair Display & Inter for Aristocratic Style with Vietnamese support */}
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
          <link 
            href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Inter:wght@300;400;500;600&display=swap" 
            rel="stylesheet" 
          />
        </head>
        <body
          // className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}
          className={`font-sans antialiased`}
        >
          <TanstackQueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </TanstackQueryProvider>
        </body>
      </html>
    </NextIntlClientProvider>
  );
}
