// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Tác dụng: Lấy thông tin đơn hàng TỔNG (API: GET /platform/orders/{id}/detail)
	GetOrderByID(ctx context.Context, id string) (Orders, error)
	// Tác dụng: Lấy danh sách ID đơn hàng TỔNG (Dùng nội bộ để truy vấn CSDL khác)
	// ĐÃ SỬA: Sửa 'ANY(sqlc.slice())' thành 'IN (sqlc.slice())'
	GetOrderIDsFromShopOrders(ctx context.Context, shopOrderIds []string) ([]string, error)
	// Tác dụng: Lấy các sản phẩm của 1 đơn hàng Shop (API: GET /shop/orders/{id}/enriched)
	GetOrderItemsByShopOrderID(ctx context.Context, shopOrderID string) ([]OrderItems, error)
	GetPlatformGMVTimeSeries(ctx context.Context, arg GetPlatformGMVTimeSeriesParams) ([]GetPlatformGMVTimeSeriesRow, error)
	// =================================================================
	// II. API CHO SÀN (Platform-facing APIs)
	// =================================================================
	// Tác dụng: Lấy tổng quan GMV và Đơn hàng toàn Sàn (API: GET /platform/overview)
	GetPlatformOrderOverview(ctx context.Context, arg GetPlatformOrderOverviewParams) (GetPlatformOrderOverviewRow, error)
	// Tác dụng: Xếp hạng sản phẩm hot nhất toàn Sàn (API: GET /platform/ranking/products)
	GetPlatformTopProductsByQuantity(ctx context.Context, arg GetPlatformTopProductsByQuantityParams) ([]GetPlatformTopProductsByQuantityRow, error)
	// Tác dụng: Xếp hạng Shop theo Doanh thu GMV (API: GET /platform/ranking/shops)
	GetPlatformTopShopsByGMV(ctx context.Context, arg GetPlatformTopShopsByGMVParams) ([]GetPlatformTopShopsByGMVRow, error)
	// Tác dụng: Xếp hạng khách hàng chi tiêu nhiều nhất (API: GET /platform/ranking/users)
	GetPlatformTopUsersBySpend(ctx context.Context, arg GetPlatformTopUsersBySpendParams) ([]GetPlatformTopUsersBySpendRow, error)
	// TácG: Thống kê hiệu suất voucher Sàn (API: GET /platform/vouchers/performance/platform)
	GetPlatformVoucherPerformance(ctx context.Context, arg GetPlatformVoucherPerformanceParams) (GetPlatformVoucherPerformanceRow, error)
	// Tác dụng: Lấy chi tiết 1 đơn hàng của Shop (API: GET /shop/orders/{id}/enriched)
	GetShopOrderByID(ctx context.Context, arg GetShopOrderByIDParams) (ShopOrders, error)
	// Tác dụng: Lấy danh sách ID đơn hàng của Shop (Dùng nội bộ để truy vấn CSDL khác)
	GetShopOrderIDs(ctx context.Context, shopID string) ([]string, error)
	// =================================================================
	// I. API CHO SHOP (Shop-facing APIs)
	// =================================================================
	// Tác dụng: Lấy chỉ số tổng quan cho Dashboard của Shop (API: GET /shop/overview)
	GetShopOrderOverview(ctx context.Context, arg GetShopOrderOverviewParams) (GetShopOrderOverviewRow, error)
	// Tác dụng: Lấy các đơn hàng SHOP con của đơn hàng TỔNG (API: GET /platform/orders/{id}/detail)
	GetShopOrdersByOrderID(ctx context.Context, orderID string) ([]ShopOrders, error)
	// Tác dụng: Lấy dữ liệu doanh thu GMV theo ngày để vẽ biểu đồ (API: GET /shop/revenue/timeseries)
	GetShopRevenueTimeSeries(ctx context.Context, arg GetShopRevenueTimeSeriesParams) ([]GetShopRevenueTimeSeriesRow, error)
	// Tác dụng: Xếp hạng sản phẩm theo Số lượng bán (API: GET /shop/ranking/products/by-quantity)
	GetShopTopProductsByQuantity(ctx context.Context, arg GetShopTopProductsByQuantityParams) ([]GetShopTopProductsByQuantityRow, error)
	// Tác dụng: Xếp hạng sản phẩm theo Doanh thu (API: GET /shop/ranking/products/by-revenue)
	GetShopTopProductsByRevenue(ctx context.Context, arg GetShopTopProductsByRevenueParams) ([]GetShopTopProductsByRevenueRow, error)
	// Tác dụng: Lấy lịch sử sử dụng của 1 voucher (API: GET /shop/vouchers/{id}/detail)
	GetVoucherUsageHistory(ctx context.Context, arg GetVoucherUsageHistoryParams) ([]VoucherUsageHistory, error)
	// Tác dụng: Thống kê hiệu suất voucher của Shop (API: GET /shop/vouchers/performance)
	// Lưu ý: CSDL voucher_usage_history thiếu shop_order_id, nên chúng ta join bằng voucher_id
	GetVoucherUsagePerformanceByOwner(ctx context.Context, arg GetVoucherUsagePerformanceByOwnerParams) (GetVoucherUsagePerformanceByOwnerRow, error)
	// Tác dụng: Lấy danh sách TẤT CẢ đơn hàng trên Sàn (API: GET /platform/orders)
	ListPlatformOrders(ctx context.Context, arg ListPlatformOrdersParams) ([]ShopOrders, error)
	// =================================================================
	// II. API CHO SÀN (Platform-facing APIs)
	// =================================================================
	// Tác dụng: Lấy tất cả voucher trên Sàn (API: GET /platform/vouchers)
	// ĐÃ SỬA: Bỏ các cast '::text'
	ListPlatformVouchers(ctx context.Context, arg ListPlatformVouchersParams) ([]Vouchers, error)
	// Tác dụng: Lấy danh sách đơn hàng (phân trang) cho Shop (API: GET /shop/orders)
	ListShopOrders(ctx context.Context, arg ListShopOrdersParams) ([]ShopOrders, error)
	// =================================================================
	// I. API CHO SHOP (Shop-facing APIs)
	// =================================================================
	// Tác dụng: Lấy danh sách voucher Shop đã tạo (API: GET /shop/vouchers)
	ListVouchersByOwner(ctx context.Context, arg ListVouchersByOwnerParams) ([]Vouchers, error)
}

var _ Querier = (*Queries)(nil)
