// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

// Lưu trữ các phiếu phản hồi (tickets) từ khách hàng
type CustomerFeedback struct {
	// UUID, Khóa chính của phiếu phản hồi
	ID string `json:"id"`
	// ID của người dùng (nếu đã đăng nhập)
	UserID sql.NullString `json:"user_id"`
	// Email của người dùng (nếu đã đăng nhập)
	Email sql.NullString `json:"email"`
	// Số điện thoại của người dùng (nếu đã đăng nhập)
	Phone sql.NullString `json:"phone"`
	// Phân loại (ví dụ: BUG, COMPLAINT, SUGGESTION)
	Category string `json:"category"`
	// Nội dung chi tiết khách hàng nhập từ form
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// Lưu trữ đánh giá Like/Dislike (và context) cho từng kết quả (event) của Agent
type MessageRatings struct {
	ID uint64 `json:"id"`
	// FK (logic) tới "events" ADK. Vẫn RẤT QUAN TRỌNG để đội ngũ dev debug.
	EventID string `json:"event_id"`
	// FK (logic) tới "sessions" ADK. Dùng để xem toàn bộ lịch sử hội thoại.
	SessionID string `json:"session_id"`
	// ID của người dùng (nếu đã đăng nhập)
	UserID sql.NullString `json:"user_id"`
	// Đánh giá (1 = Like, -1 = Dislike)
	Rating int8 `json:"rating"`
	// Snapshot câu hỏi/prompt của người dùng đã dẫn đến câu trả lời này
	UserPrompt sql.NullString `json:"user_prompt"`
	// Snapshot câu trả lời của Agent đã được đánh giá
	AgentResponse sql.NullString `json:"agent_response"`
	CreatedAt     time.Time      `json:"created_at"`
}
