// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// =================================================================
	// SQLC QUERIES FOR CUSTOMER_FEEDBACK
	// =================================================================
	CreateCustomerFeedback(ctx context.Context, arg CreateCustomerFeedbackParams) error
	// =================================================================
	// SQLC QUERIES FOR MESSAGE_RATINGS
	// =================================================================
	CreateMessageRating(ctx context.Context, arg CreateMessageRatingParams) error
	// Lấy chi tiết 1 feedback
	GetCustomerFeedbackByID(ctx context.Context, id string) (CustomerFeedback, error)
	// Thống kê tổng quan feedback
	GetCustomerFeedbackStats(ctx context.Context, arg GetCustomerFeedbackStatsParams) (GetCustomerFeedbackStatsRow, error)
	// Thống kê feedback theo category
	GetCustomerFeedbacksByCategory(ctx context.Context, arg GetCustomerFeedbacksByCategoryParams) ([]GetCustomerFeedbacksByCategoryRow, error)
	// Thống kê tổng quan đánh giá message ratings
	GetMessageRatingStats(ctx context.Context, arg GetMessageRatingStatsParams) (GetMessageRatingStatsRow, error)
	// Lấy danh sách ratings theo session để xem chi tiết
	GetMessageRatingsBySession(ctx context.Context, arg GetMessageRatingsBySessionParams) ([]MessageRatings, error)
	// Thống kê theo thời gian (theo ngày)
	GetMessageRatingsTimeSeries(ctx context.Context, arg GetMessageRatingsTimeSeriesParams) ([]GetMessageRatingsTimeSeriesRow, error)
	// Lấy danh sách feedback cho Admin xem
	ListCustomerFeedbacks(ctx context.Context, arg ListCustomerFeedbacksParams) ([]CustomerFeedback, error)
}

var _ Querier = (*Queries)(nil)
