// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_analitics.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getDashboardStats = `-- name: GetDashboardStats :one

SELECT 
    COUNT(DISTINCT session_id) AS total_sessions,
    
    -- Ép kiểu về SIGNED (số nguyên) và mặc định là 0 nếu NULL
    CAST(COALESCE(SUM(CASE WHEN author = 'user' THEN 1 ELSE 0 END), 0) AS SIGNED) AS total_user_messages,
    
    -- Tương tự cho agent
    CAST(COALESCE(SUM(CASE WHEN author = 'Host_Agent' THEN 1 ELSE 0 END), 0) AS SIGNED) AS total_agent_messages
FROM events
WHERE 
    (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
`

type GetDashboardStatsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type GetDashboardStatsRow struct {
	TotalSessions      int64 `json:"total_sessions"`
	TotalUserMessages  int64 `json:"total_user_messages"`
	TotalAgentMessages int64 `json:"total_agent_messages"`
}

// ==============================================================
// 1. THỐNG KÊ TỔNG QUAN (DASHBOARD)
// Tác dụng: Lấy tổng số session, tin nhắn user, tin nhắn agent.
// Linh hoạt: Có thể lọc theo khoảng thời gian hoặc lấy toàn bộ.
// ==============================================================
func (q *Queries) GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDashboardStats,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	var i GetDashboardStatsRow
	err := row.Scan(&i.TotalSessions, &i.TotalUserMessages, &i.TotalAgentMessages)
	return i, err
}

const getMessageVolumeByHour = `-- name: GetMessageVolumeByHour :many

SELECT 
    HOUR(timestamp) AS hour_of_day,
    COUNT(*) AS message_count
FROM events
WHERE 
    author = 'user'
    AND (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
GROUP BY hour_of_day
ORDER BY hour_of_day ASC
`

type GetMessageVolumeByHourParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type GetMessageVolumeByHourRow struct {
	HourOfDay    int32 `json:"hour_of_day"`
	MessageCount int64 `json:"message_count"`
}

// ==============================================================
// 2. BIỂU ĐỒ HEATMAP (THEO GIỜ TRONG NGÀY)
// Tác dụng: Xem mật độ tin nhắn theo giờ.
// ==============================================================
func (q *Queries) GetMessageVolumeByHour(ctx context.Context, arg GetMessageVolumeByHourParams) ([]GetMessageVolumeByHourRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessageVolumeByHour,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageVolumeByHourRow
	for rows.Next() {
		var i GetMessageVolumeByHourRow
		if err := rows.Scan(&i.HourOfDay, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseIntentStats = `-- name: GetPurchaseIntentStats :many

SELECT 
    custom_metadata->>'$.purchase_intent' AS purchase_intent,
    COUNT(*) AS count
FROM events
WHERE 
    author = 'user' 
    AND custom_metadata IS NOT NULL
    AND (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
GROUP BY purchase_intent
ORDER BY count DESC
`

type GetPurchaseIntentStatsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type GetPurchaseIntentStatsRow struct {
	PurchaseIntent json.RawMessage `json:"purchase_intent"`
	Count          int64           `json:"count"`
}

// ==============================================================
// 5. PHÂN TÍCH Ý ĐỊNH MUA HÀNG (PURCHASE INTENT)
// Tác dụng: Đếm số lượng theo mức độ Intent (High, Medium, Low).
// ==============================================================
func (q *Queries) GetPurchaseIntentStats(ctx context.Context, arg GetPurchaseIntentStatsParams) ([]GetPurchaseIntentStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPurchaseIntentStats,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPurchaseIntentStatsRow
	for rows.Next() {
		var i GetPurchaseIntentStatsRow
		if err := rows.Scan(&i.PurchaseIntent, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopActiveUsers = `-- name: GetTopActiveUsers :many

SELECT 
    user_id, 
    COUNT(*) AS message_count
FROM events 
WHERE 
    author = 'user'
    AND (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
GROUP BY user_id 
ORDER BY message_count DESC 
LIMIT ?
`

type GetTopActiveUsersParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	Limit     int32        `json:"limit"`
}

type GetTopActiveUsersRow struct {
	UserID       string `json:"user_id"`
	MessageCount int64  `json:"message_count"`
}

// ==============================================================
// 3. TOP NGƯỜI DÙNG TÍCH CỰC
// Tác dụng: Tìm User nhắn nhiều nhất.
// Tham số limit_count bắt buộc để giới hạn số lượng trả về (ví dụ: Top 10).
// ==============================================================
func (q *Queries) GetTopActiveUsers(ctx context.Context, arg GetTopActiveUsersParams) ([]GetTopActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopActiveUsers,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopActiveUsersRow
	for rows.Next() {
		var i GetTopActiveUsersRow
		if err := rows.Scan(&i.UserID, &i.MessageCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMentionedCategories = `-- name: GetTopMentionedCategories :many

SELECT 
    custom_metadata
FROM events
WHERE 
    author = 'user' 
    AND custom_metadata IS NOT NULL
    AND (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
`

type GetTopMentionedCategoriesParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

// ==============================================================
// 6. TOP SẢN PHẨM ĐƯỢC NHẮC ĐẾN (ENTITIES)
// Tác dụng: Trích xuất tên sản phẩm/danh mục từ mảng entities trong JSON.
// ==============================================================
func (q *Queries) GetTopMentionedCategories(ctx context.Context, arg GetTopMentionedCategoriesParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getTopMentionedCategories,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var custom_metadata sql.NullString
		if err := rows.Scan(&custom_metadata); err != nil {
			return nil, err
		}
		items = append(items, custom_metadata)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicStats = `-- name: GetTopicStats :many

SELECT 
    custom_metadata->>'$.topic' AS topic,
    COUNT(*) AS count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS percentage
FROM events
WHERE 
    author = 'user' 
    AND custom_metadata IS NOT NULL
    AND (? IS NULL OR timestamp >= ?)
    AND (? IS NULL OR timestamp <= ?)
GROUP BY topic
ORDER BY count DESC
`

type GetTopicStatsParams struct {
	StartTime sql.NullTime `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
}

type GetTopicStatsRow struct {
	Topic      json.RawMessage `json:"topic"`
	Count      int64           `json:"count"`
	Percentage float64         `json:"percentage"`
}

// ==============================================================
// 4. PHÂN TÍCH CHỦ ĐỀ (TOPIC ANALYSIS)
// Tác dụng: Thống kê các Topic từ cột JSON custom_metadata.
// ==============================================================
func (q *Queries) GetTopicStats(ctx context.Context, arg GetTopicStatsParams) ([]GetTopicStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTopicStats,
		arg.StartTime,
		arg.StartTime,
		arg.EndTime,
		arg.EndTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopicStatsRow
	for rows.Next() {
		var i GetTopicStatsRow
		if err := rows.Scan(&i.Topic, &i.Count, &i.Percentage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
