// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AppStates struct {
	AppName    string    `json:"app_name"`
	State      string    `json:"state"`
	UpdateTime time.Time `json:"update_time"`
}

type Events struct {
	ID                     string         `json:"id"`
	AppName                string         `json:"app_name"`
	UserID                 string         `json:"user_id"`
	SessionID              string         `json:"session_id"`
	InvocationID           string         `json:"invocation_id"`
	Author                 string         `json:"author"`
	Actions                sql.NullString `json:"actions"`
	LongRunningToolIdsJson sql.NullString `json:"long_running_tool_ids_json"`
	Branch                 sql.NullString `json:"branch"`
	Timestamp              time.Time      `json:"timestamp"`
	Content                sql.NullString `json:"content"`
	GroundingMetadata      sql.NullString `json:"grounding_metadata"`
	CustomMetadata         sql.NullString `json:"custom_metadata"`
	Partial                sql.NullBool   `json:"partial"`
	TurnComplete           sql.NullBool   `json:"turn_complete"`
	ErrorCode              sql.NullString `json:"error_code"`
	ErrorMessage           sql.NullString `json:"error_message"`
	Interrupted            sql.NullBool   `json:"interrupted"`
}

type Sessions struct {
	AppName    string    `json:"app_name"`
	UserID     string    `json:"user_id"`
	ID         string    `json:"id"`
	State      string    `json:"state"`
	CreateTime time.Time `json:"create_time"`
	UpdateTime time.Time `json:"update_time"`
}

type UserStates struct {
	AppName    string    `json:"app_name"`
	UserID     string    `json:"user_id"`
	State      string    `json:"state"`
	UpdateTime time.Time `json:"update_time"`
}
