// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ==============================================================
	// 1. THỐNG KÊ TỔNG QUAN (DASHBOARD)
	// Tác dụng: Lấy tổng số session, tin nhắn user, tin nhắn agent.
	// Linh hoạt: Có thể lọc theo khoảng thời gian hoặc lấy toàn bộ.
	// ==============================================================
	GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error)
	// ==============================================================
	// 2. BIỂU ĐỒ HEATMAP (THEO GIỜ TRONG NGÀY)
	// Tác dụng: Xem mật độ tin nhắn theo giờ.
	// ==============================================================
	GetMessageVolumeByHour(ctx context.Context, arg GetMessageVolumeByHourParams) ([]GetMessageVolumeByHourRow, error)
	// ==============================================================
	// 5. PHÂN TÍCH Ý ĐỊNH MUA HÀNG (PURCHASE INTENT)
	// Tác dụng: Đếm số lượng theo mức độ Intent (High, Medium, Low).
	// ==============================================================
	GetPurchaseIntentStats(ctx context.Context, arg GetPurchaseIntentStatsParams) ([]GetPurchaseIntentStatsRow, error)
	// ==============================================================
	// 3. TOP NGƯỜI DÙNG TÍCH CỰC
	// Tác dụng: Tìm User nhắn nhiều nhất.
	// Tham số limit_count bắt buộc để giới hạn số lượng trả về (ví dụ: Top 10).
	// ==============================================================
	GetTopActiveUsers(ctx context.Context, arg GetTopActiveUsersParams) ([]GetTopActiveUsersRow, error)
	// ==============================================================
	// 6. TOP SẢN PHẨM ĐƯỢC NHẮC ĐẾN (ENTITIES)
	// Tác dụng: Trích xuất tên sản phẩm/danh mục từ mảng entities trong JSON.
	// ==============================================================
	GetTopMentionedCategories(ctx context.Context, arg GetTopMentionedCategoriesParams) ([]sql.NullString, error)
	// ==============================================================
	// 4. PHÂN TÍCH CHỦ ĐỀ (TOPIC ANALYSIS)
	// Tác dụng: Thống kê các Topic từ cột JSON custom_metadata.
	// ==============================================================
	GetTopicStats(ctx context.Context, arg GetTopicStatsParams) ([]GetTopicStatsRow, error)
}

var _ Querier = (*Queries)(nil)
