// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brand.sql

package db

import (
	"context"
	"database/sql"
)

const countBrands = `-- name: CountBrands :one
SELECT COUNT(*) AS total FROM brand
`

func (q *Queries) CountBrands(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBrands)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createBrand = `-- name: CreateBrand :exec
INSERT INTO brand (
  brand_id, name, code, image, create_date, update_date
) VALUES (
  ?, ?, ?, ?, NOW(), NOW()
)
`

type CreateBrandParams struct {
	BrandID string         `json:"brand_id"`
	Name    string         `json:"name"`
	Code    string         `json:"code"`
	Image   sql.NullString `json:"image"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) error {
	_, err := q.db.ExecContext(ctx, createBrand,
		arg.BrandID,
		arg.Name,
		arg.Code,
		arg.Image,
	)
	return err
}

const deleteBrand = `-- name: DeleteBrand :exec
DELETE FROM brand
WHERE brand_id = ?
`

func (q *Queries) DeleteBrand(ctx context.Context, brandID string) error {
	_, err := q.db.ExecContext(ctx, deleteBrand, brandID)
	return err
}

const getBrand = `-- name: GetBrand :one
SELECT brand_id, name, code, image, create_date, update_date FROM brand
WHERE brand_id = ? LIMIT 1
`

func (q *Queries) GetBrand(ctx context.Context, brandID string) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrand, brandID)
	var i Brand
	err := row.Scan(
		&i.BrandID,
		&i.Name,
		&i.Code,
		&i.Image,
		&i.CreateDate,
		&i.UpdateDate,
	)
	return i, err
}

const getBrandByCode = `-- name: GetBrandByCode :one
SELECT brand_id, name, code, image, create_date, update_date FROM brand
WHERE code = ? LIMIT 1
`

func (q *Queries) GetBrandByCode(ctx context.Context, code string) (Brand, error) {
	row := q.db.QueryRowContext(ctx, getBrandByCode, code)
	var i Brand
	err := row.Scan(
		&i.BrandID,
		&i.Name,
		&i.Code,
		&i.Image,
		&i.CreateDate,
		&i.UpdateDate,
	)
	return i, err
}

const listBrands = `-- name: ListBrands :many
SELECT brand_id, name, code, image, create_date, update_date FROM brand
ORDER BY create_date DESC
`

func (q *Queries) ListBrands(ctx context.Context) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, listBrands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.Image,
			&i.CreateDate,
			&i.UpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBrandsPaged = `-- name: ListBrandsPaged :many
SELECT brand_id, name, code, image, create_date, update_date FROM brand
ORDER BY create_date DESC
LIMIT ? OFFSET ?
`

type ListBrandsPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBrandsPaged(ctx context.Context, arg ListBrandsPagedParams) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, listBrandsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.Image,
			&i.CreateDate,
			&i.UpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBrandsByName = `-- name: SearchBrandsByName :many
SELECT brand_id, name, code, image, create_date, update_date FROM brand
WHERE name LIKE '%' || ? || '%'
ORDER BY name
`

func (q *Queries) SearchBrandsByName(ctx context.Context, dollar_1 interface{}) ([]Brand, error) {
	rows, err := q.db.QueryContext(ctx, searchBrandsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.BrandID,
			&i.Name,
			&i.Code,
			&i.Image,
			&i.CreateDate,
			&i.UpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBrand = `-- name: UpdateBrand :exec
UPDATE brand
SET 
  name = COALESCE(?, name),
  code = COALESCE(?, code),
  image = COALESCE(?, image),
  update_date = NOW()
WHERE brand_id = ?
`

type UpdateBrandParams struct {
	Name    sql.NullString `json:"name"`
	Code    sql.NullString `json:"code"`
	Image   sql.NullString `json:"image"`
	BrandID string         `json:"brand_id"`
}

func (q *Queries) UpdateBrand(ctx context.Context, arg UpdateBrandParams) error {
	_, err := q.db.ExecContext(ctx, updateBrand,
		arg.Name,
		arg.Code,
		arg.Image,
		arg.BrandID,
	)
	return err
}

const updateBrandImage = `-- name: UpdateBrandImage :exec
UPDATE brand
SET image = ?, update_date = NOW()
WHERE brand_id = ?
`

type UpdateBrandImageParams struct {
	Image   sql.NullString `json:"image"`
	BrandID string         `json:"brand_id"`
}

func (q *Queries) UpdateBrandImage(ctx context.Context, arg UpdateBrandImageParams) error {
	_, err := q.db.ExecContext(ctx, updateBrandImage, arg.Image, arg.BrandID)
	return err
}
