// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package db

import (
	"context"
	"database/sql"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) AS total FROM category
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCategory = `-- name: CreateCategory :exec
INSERT INTO category (
  category_id, name, ` + "`" + `key` + "`" + `, ` + "`" + `path` + "`" + `, parent, image
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateCategoryParams struct {
	CategoryID string         `json:"category_id"`
	Name       string         `json:"name"`
	Key        string         `json:"key"`
	Path       sql.NullString `json:"path"`
	Parent     sql.NullString `json:"parent"`
	Image      sql.NullString `json:"image"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, createCategory,
		arg.CategoryID,
		arg.Name,
		arg.Key,
		arg.Path,
		arg.Parent,
		arg.Image,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM category
WHERE category_id = ?
`

func (q *Queries) DeleteCategory(ctx context.Context, categoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, categoryID)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
WHERE category_id = ? LIMIT 1
`

func (q *Queries) GetCategory(ctx context.Context, categoryID string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, categoryID)
	var i Category
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Key,
		&i.Path,
		&i.Parent,
		&i.Image,
	)
	return i, err
}

const getRootCategories = `-- name: GetRootCategories :many
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
WHERE parent IS NULL
`

func (q *Queries) GetRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Key,
			&i.Path,
			&i.Parent,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCategories = `-- name: GetSubCategories :many
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
WHERE parent = ?
`

func (q *Queries) GetSubCategories(ctx context.Context, parent sql.NullString) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getSubCategories, parent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Key,
			&i.Path,
			&i.Parent,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Key,
			&i.Path,
			&i.Parent,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesPaged = `-- name: ListCategoriesPaged :many
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
ORDER BY name
LIMIT ? OFFSET ?
`

type ListCategoriesPagedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCategoriesPaged(ctx context.Context, arg ListCategoriesPagedParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Key,
			&i.Path,
			&i.Parent,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCategoriesByName = `-- name: SearchCategoriesByName :many
SELECT category_id, name, ` + "`" + `key` + "`" + `, path, parent, image FROM category
WHERE name LIKE '%' || ? || '%'
ORDER BY name
`

func (q *Queries) SearchCategoriesByName(ctx context.Context, dollar_1 interface{}) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, searchCategoriesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Key,
			&i.Path,
			&i.Parent,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE category
SET 
  name = COALESCE(?, name),
  ` + "`" + `key` + "`" + ` = COALESCE(?, ` + "`" + `key` + "`" + `),
  ` + "`" + `path` + "`" + ` = COALESCE(?, ` + "`" + `path` + "`" + `),
  parent = COALESCE(?, parent),
  image = COALESCE(?, image)
WHERE category_id = ?
`

type UpdateCategoryParams struct {
	Name       sql.NullString `json:"name"`
	Key        sql.NullString `json:"key"`
	Path       sql.NullString `json:"path"`
	Parent     sql.NullString `json:"parent"`
	Image      sql.NullString `json:"image"`
	CategoryID string         `json:"category_id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Key,
		arg.Path,
		arg.Parent,
		arg.Image,
		arg.CategoryID,
	)
	return err
}

const updateCategoryImage = `-- name: UpdateCategoryImage :exec
UPDATE category
SET image = ?
WHERE category_id = ?
`

type UpdateCategoryImageParams struct {
	Image      sql.NullString `json:"image"`
	CategoryID string         `json:"category_id"`
}

func (q *Queries) UpdateCategoryImage(ctx context.Context, arg UpdateCategoryImageParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryImage, arg.Image, arg.CategoryID)
	return err
}

const updateCategoryParent = `-- name: UpdateCategoryParent :exec
UPDATE category
SET parent = ?
WHERE category_id = ?
`

type UpdateCategoryParentParams struct {
	Parent     sql.NullString `json:"parent"`
	CategoryID string         `json:"category_id"`
}

func (q *Queries) UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) error {
	_, err := q.db.ExecContext(ctx, updateCategoryParent, arg.Parent, arg.CategoryID)
	return err
}
