// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type ProductDeleteStatus string

const (
	ProductDeleteStatusActive  ProductDeleteStatus = "Active"
	ProductDeleteStatusDeleted ProductDeleteStatus = "Deleted"
)

func (e *ProductDeleteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductDeleteStatus(s)
	case string:
		*e = ProductDeleteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductDeleteStatus: %T", src)
	}
	return nil
}

type NullProductDeleteStatus struct {
	ProductDeleteStatus ProductDeleteStatus `json:"product_delete_status"`
	Valid               bool                `json:"valid"` // Valid is true if ProductDeleteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductDeleteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductDeleteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductDeleteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductDeleteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductDeleteStatus), nil
}

type Brand struct {
	BrandID    string         `json:"brand_id"`
	Name       string         `json:"name"`
	Code       string         `json:"code"`
	Image      sql.NullString `json:"image"`
	CreateDate sql.NullTime   `json:"create_date"`
	UpdateDate sql.NullTime   `json:"update_date"`
}

type Category struct {
	CategoryID string         `json:"category_id"`
	Name       string         `json:"name"`
	Key        string         `json:"key"`
	Path       sql.NullString `json:"path"`
	Parent     sql.NullString `json:"parent"`
	Image      sql.NullString `json:"image"`
}

type OptionValue struct {
	ID         string         `json:"id"`
	OptionName string         `json:"option_name"`
	Value      string         `json:"value"`
	ProductID  string         `json:"product_id"`
	Image      sql.NullString `json:"image"`
}

type Product struct {
	ID                        string                  `json:"id"`
	Name                      string                  `json:"name"`
	Key                       string                  `json:"key"`
	Description               sql.NullString          `json:"description"`
	ShortDescription          sql.NullString          `json:"short_description"`
	BrandID                   sql.NullString          `json:"brand_id"`
	CategoryID                string                  `json:"category_id"`
	ShopID                    string                  `json:"shop_id"`
	Image                     string                  `json:"image"`
	Media                     sql.NullString          `json:"media"`
	DeleteStatus              NullProductDeleteStatus `json:"delete_status"`
	ProductIsPermissionReturn sql.NullBool            `json:"product_is_permission_return"`
	ProductIsPermissionCheck  sql.NullBool            `json:"product_is_permission_check"`
	CreateDate                sql.NullTime            `json:"create_date"`
	UpdateDate                sql.NullTime            `json:"update_date"`
	CreateBy                  sql.NullString          `json:"create_by"`
	UpdateBy                  sql.NullString          `json:"update_by"`
	TotalSold                 int64                   `json:"total_sold"`
}

type ProductSku struct {
	ID               string         `json:"id"`
	ProductID        string         `json:"product_id"`
	SkuCode          string         `json:"sku_code"`
	Price            float64        `json:"price"`
	Quantity         int32          `json:"quantity"`
	QuantityReserver int32          `json:"quantity_reserver"`
	SkuName          sql.NullString `json:"sku_name"`
	Weight           float64        `json:"weight"`
	CreateDate       sql.NullTime   `json:"create_date"`
	UpdateDate       sql.NullTime   `json:"update_date"`
}

type SkuAttr struct {
	SkuID         string `json:"sku_id"`
	OptionValueID string `json:"option_value_id"`
	ProductID     string `json:"product_id"`
}
