// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: option_value.sql

package db

import (
	"context"
	"database/sql"
)

const createOptionValue = `-- name: CreateOptionValue :exec

INSERT INTO option_value (
  id, option_name, ` + "`" + `value` + "`" + `, product_id, image
) VALUES (
  ?,
  ?,
  ?,
  ?,
  ?
  )
`

type CreateOptionValueParams struct {
	ID         string         `json:"id"`
	OptionName string         `json:"option_name"`
	Value      string         `json:"value"`
	ProductID  string         `json:"product_id"`
	Image      sql.NullString `json:"image"`
}

// OPTION VALUE (option_value) CRUD
func (q *Queries) CreateOptionValue(ctx context.Context, arg CreateOptionValueParams) error {
	_, err := q.db.ExecContext(ctx, createOptionValue,
		arg.ID,
		arg.OptionName,
		arg.Value,
		arg.ProductID,
		arg.Image,
	)
	return err
}

const deleteOptionValue = `-- name: DeleteOptionValue :exec
DELETE FROM option_value WHERE id = ?
`

func (q *Queries) DeleteOptionValue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOptionValue, id)
	return err
}

const listOptionValuesByProductID = `-- name: ListOptionValuesByProductID :many
SELECT id, option_name, value, product_id, image FROM option_value WHERE product_id = ? ORDER BY option_name
`

func (q *Queries) ListOptionValuesByProductID(ctx context.Context, productID string) ([]OptionValue, error) {
	rows, err := q.db.QueryContext(ctx, listOptionValuesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OptionValue
	for rows.Next() {
		var i OptionValue
		if err := rows.Scan(
			&i.ID,
			&i.OptionName,
			&i.Value,
			&i.ProductID,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOptionValue = `-- name: UpdateOptionValue :exec
UPDATE option_value
SET
  option_name = COALESCE(?, option_name),
  ` + "`" + `value` + "`" + ` = COALESCE(?, ` + "`" + `value` + "`" + `),
  image = COALESCE(?, image)
WHERE id = ?
`

type UpdateOptionValueParams struct {
	OptionName sql.NullString `json:"option_name"`
	Value      sql.NullString `json:"value"`
	Image      sql.NullString `json:"image"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateOptionValue(ctx context.Context, arg UpdateOptionValueParams) error {
	_, err := q.db.ExecContext(ctx, updateOptionValue,
		arg.OptionName,
		arg.Value,
		arg.Image,
		arg.ID,
	)
	return err
}
