// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_sku.sql

package db

import (
	"context"
	"database/sql"
)

const createProductSKU = `-- name: CreateProductSKU :exec

INSERT INTO product_sku (
  id, product_id, sku_code, price, quantity, weight
) VALUES (
  ?,
  ?,
  ?,
  ?, 
  ?, 
  ?
)
`

type CreateProductSKUParams struct {
	ID        string  `json:"id"`
	ProductID string  `json:"product_id"`
	SkuCode   string  `json:"sku_code"`
	Price     float64 `json:"price"`
	Quantity  int32   `json:"quantity"`
	Weight    float64 `json:"weight"`
}

// PRODUCT SKU (product_sku) CRUD
func (q *Queries) CreateProductSKU(ctx context.Context, arg CreateProductSKUParams) error {
	_, err := q.db.ExecContext(ctx, createProductSKU,
		arg.ID,
		arg.ProductID,
		arg.SkuCode,
		arg.Price,
		arg.Quantity,
		arg.Weight,
	)
	return err
}

const deleteProductSKU = `-- name: DeleteProductSKU :exec
DELETE FROM product_sku WHERE id = ?
`

func (q *Queries) DeleteProductSKU(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProductSKU, id)
	return err
}

const getProductSKU = `-- name: GetProductSKU :one
SELECT id, product_id, sku_code, price, quantity, quantity_reserver, sku_name, weight, create_date, update_date FROM product_sku WHERE id = ? LIMIT 1
`

func (q *Queries) GetProductSKU(ctx context.Context, id string) (ProductSku, error) {
	row := q.db.QueryRowContext(ctx, getProductSKU, id)
	var i ProductSku
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.SkuCode,
		&i.Price,
		&i.Quantity,
		&i.QuantityReserver,
		&i.SkuName,
		&i.Weight,
		&i.CreateDate,
		&i.UpdateDate,
	)
	return i, err
}

const listSKUsByProduct = `-- name: ListSKUsByProduct :many
SELECT id, product_id, sku_code, price, quantity, quantity_reserver, sku_name, weight, create_date, update_date FROM product_sku
WHERE product_id = ?
ORDER BY price
`

func (q *Queries) ListSKUsByProduct(ctx context.Context, productID string) ([]ProductSku, error) {
	rows, err := q.db.QueryContext(ctx, listSKUsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductSku
	for rows.Next() {
		var i ProductSku
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.SkuCode,
			&i.Price,
			&i.Quantity,
			&i.QuantityReserver,
			&i.SkuName,
			&i.Weight,
			&i.CreateDate,
			&i.UpdateDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductSKU = `-- name: UpdateProductSKU :exec
UPDATE product_sku
SET
  sku_code = COALESCE(?, sku_code),
  price = COALESCE(?, price),
  quantity = COALESCE(?, quantity),
  quantity_reserver = COALESCE(?, quantity_reserver),
  weight = COALESCE(?, weight),
  update_date = NOW()
WHERE id = ?
`

type UpdateProductSKUParams struct {
	SkuCode          sql.NullString  `json:"sku_code"`
	Price            sql.NullFloat64 `json:"price"`
	Quantity         sql.NullInt32   `json:"quantity"`
	QuantityReserver sql.NullInt32   `json:"quantity_reserver"`
	Weight           sql.NullFloat64 `json:"weight"`
	ID               string          `json:"id"`
}

func (q *Queries) UpdateProductSKU(ctx context.Context, arg UpdateProductSKUParams) error {
	_, err := q.db.ExecContext(ctx, updateProductSKU,
		arg.SkuCode,
		arg.Price,
		arg.Quantity,
		arg.QuantityReserver,
		arg.Weight,
		arg.ID,
	)
	return err
}
