// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountBrands(ctx context.Context) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountProductsAdvanced(ctx context.Context, arg CountProductsAdvancedParams) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	// OPTION VALUE (option_value) CRUD
	CreateOptionValue(ctx context.Context, arg CreateOptionValueParams) error
	// PRODUCT CRUD & UTILS
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	// PRODUCT SKU (product_sku) CRUD
	CreateProductSKU(ctx context.Context, arg CreateProductSKUParams) error
	// SKU_ATTR (sku_attr) CRUD
	CreateSKUAttr(ctx context.Context, arg CreateSKUAttrParams) error
	DeleteBrand(ctx context.Context, brandID string) error
	DeleteCategory(ctx context.Context, categoryID string) error
	DeleteOptionValue(ctx context.Context, id string) error
	DeleteProduct(ctx context.Context, id string) error
	DeleteProductSKU(ctx context.Context, id string) error
	DeleteSKUAttr(ctx context.Context, arg DeleteSKUAttrParams) error
	GetAllProductID(ctx context.Context) ([]string, error)
	GetBrand(ctx context.Context, brandID string) (Brand, error)
	GetBrandByCode(ctx context.Context, code string) (Brand, error)
	GetCategory(ctx context.Context, categoryID string) (Category, error)
	GetProduct(ctx context.Context, id string) (GetProductRow, error)
	GetProductByKey(ctx context.Context, key string) (GetProductByKeyRow, error)
	GetProductIDs(ctx context.Context, productIds []string) ([]Product, error)
	GetProductSKU(ctx context.Context, id string) (ProductSku, error)
	GetProductStockTotal(ctx context.Context, productID string) (interface{}, error)
	GetRootCategories(ctx context.Context) ([]Category, error)
	GetSubCategories(ctx context.Context, parent sql.NullString) ([]Category, error)
	IncrementProductTotalSold(ctx context.Context, arg IncrementProductTotalSoldParams) error
	ListBrands(ctx context.Context) ([]Brand, error)
	ListBrandsPaged(ctx context.Context, arg ListBrandsPagedParams) ([]Brand, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoriesPaged(ctx context.Context, arg ListCategoriesPagedParams) ([]Category, error)
	ListOptionValuesByProductID(ctx context.Context, productID string) ([]OptionValue, error)
	ListProductsAdvanced(ctx context.Context, arg ListProductsAdvancedParams) ([]ListProductsAdvancedRow, error)
	ListSKUOptionValuesByProductID(ctx context.Context, productID string) ([]SkuAttr, error)
	ListSKUsByProduct(ctx context.Context, productID string) ([]ProductSku, error)
	SearchBrandsByName(ctx context.Context, dollar_1 interface{}) ([]Brand, error)
	SearchCategoriesByName(ctx context.Context, dollar_1 interface{}) ([]Category, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) error
	UpdateBrandImage(ctx context.Context, arg UpdateBrandImageParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCategoryImage(ctx context.Context, arg UpdateCategoryImageParams) error
	UpdateCategoryParent(ctx context.Context, arg UpdateCategoryParentParams) error
	UpdateOptionValue(ctx context.Context, arg UpdateOptionValueParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductSKU(ctx context.Context, arg UpdateProductSKUParams) error
}

var _ Querier = (*Queries)(nil)
