// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sku_attr.sql

package db

import (
	"context"
)

const createSKUAttr = `-- name: CreateSKUAttr :exec

INSERT INTO sku_attr (sku_id, option_value_id, product_id)
VALUES (?, ?, ?)
`

type CreateSKUAttrParams struct {
	SkuID         string `json:"sku_id"`
	OptionValueID string `json:"option_value_id"`
	ProductID     string `json:"product_id"`
}

// SKU_ATTR (sku_attr) CRUD
func (q *Queries) CreateSKUAttr(ctx context.Context, arg CreateSKUAttrParams) error {
	_, err := q.db.ExecContext(ctx, createSKUAttr, arg.SkuID, arg.OptionValueID, arg.ProductID)
	return err
}

const deleteSKUAttr = `-- name: DeleteSKUAttr :exec
DELETE FROM sku_attr WHERE sku_id = ? AND option_value_id = ?
`

type DeleteSKUAttrParams struct {
	SkuID         string `json:"sku_id"`
	OptionValueID string `json:"option_value_id"`
}

func (q *Queries) DeleteSKUAttr(ctx context.Context, arg DeleteSKUAttrParams) error {
	_, err := q.db.ExecContext(ctx, deleteSKUAttr, arg.SkuID, arg.OptionValueID)
	return err
}

const listSKUOptionValuesByProductID = `-- name: ListSKUOptionValuesByProductID :many
SELECT sku_id, option_value_id, product_id
FROM sku_attr sa
WHERE sa.product_id = ?
`

func (q *Queries) ListSKUOptionValuesByProductID(ctx context.Context, productID string) ([]SkuAttr, error) {
	rows, err := q.db.QueryContext(ctx, listSKUOptionValuesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkuAttr
	for rows.Next() {
		var i SkuAttr
		if err := rows.Scan(&i.SkuID, &i.OptionValueID, &i.ProductID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
