import Layout from "@/resources/layout/ContainerLayout";
import Footer from "@/resources/layout/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "new app",
    description: "Generated by new app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <Layout>
            <div>
            {children}
            </div>
        </Layout>
    );
}
