SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS brand;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS option_value;
DROP TABLE IF EXISTS product_sku;
DROP TABLE IF EXISTS sku_attr;

SET FOREIGN_KEY_CHECKS = 1;