variables:
  PAYMENT_NAME: "api-payment-service" 
  PAYMENT_IMAGE: ${REGISTRY_USER}/${PAYMENT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  PAYMENT_CONTAINER: ${CI_PROJECT_NAME}___${PAYMENT_NAME}   
  PAYMENT_HOST_PORT: "9003"
  PAYMENT_CONTAINER_PORT: "9003"
  SERVICE_PATH: "api_system/ecom_payment_service"

build_payment:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - echo "Building payment Service..."
    - cd $SERVICE_PATH 
    - docker build -t $PAYMENT_IMAGE .
    - docker push $PAYMENT_IMAGE
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*

deploy_payment:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull $PAYMENT_IMAGE
    - docker rm -f $PAYMENT_CONTAINER || true
    - docker run --name $PAYMENT_CONTAINER \
      --env-file $ENV_FILE_PAYMENT \
      --restart unless-stopped \
      -d -p $PAYMENT_HOST_PORT:$PAYMENT_CONTAINER_PORT \
      $PAYMENT_IMAGE
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*

showlog_payment:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 10
    - docker logs $PAYMENT_CONTAINER
  tags:
    - server-dev
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*