variables:
  PRODUCT_NAME: "api-payment-service" 
  PRODUCT_IMAGE: ${REGISTRY_USER}/${PRODUCT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  PRODUCT_CONTAINER: ${PRODUCT_NAME}   
  PRODUCT_HOST_PORT: "9003"
  PRODUCT_CONTAINER_PORT: "9003"
  SERVICE_PATH: "api_system/ecom_payment_service"

build_payment:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - echo "Building payment Service..."
    - cd $SERVICE_PATH 
    - docker build -t $PRODUCT_IMAGE .
    - docker push $PRODUCT_IMAGE
  tags:
    - lab-server
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*

deploy_payment:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  before_script:
    - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  script:
    - docker pull $PRODUCT_IMAGE
    - docker rm -f $PRODUCT_CONTAINER || true
    - docker run --name $PRODUCT_CONTAINER \
      --env-file $ENV_FILE_PAYMENT \
      --restart unless-stopped \
      -d -p $PRODUCT_HOST_PORT:$PRODUCT_CONTAINER_PORT \
      $PRODUCT_IMAGE
  tags:
    - lab-server
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*

showlog_payment:
  stage: showlog
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 10
    - docker logs $PRODUCT_CONTAINER
  tags:
    - lab-server
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - api_system/ecom_payment_service/**/*