// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	// =================================================================
	// Queries for `account_ledgers` table
	// =================================================================
	CreateLedger(ctx context.Context, arg CreateLedgerParams) error
	// =================================================================
	// Queries for `ledger_entries` table
	// =================================================================
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error
	// =================================================================
	// Queries for `order_platform_costs` table (New Table)
	// =================================================================
	// Records the total costs incurred by the platform for a specific order payment.
	CreateOrderPlatformCost(ctx context.Context, arg CreateOrderPlatformCostParams) error
	// =================================================================
	// Queries for `shop_order_settlements` table
	// =================================================================
	// Creates the financial snapshot and settlement record for a shop order.
	CreateShopOrderSettlement(ctx context.Context, arg CreateShopOrderSettlementParams) error
	// =================================================================
	// Queries for `transactions` table
	// =================================================================
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	GetExpiredPendingTransactions(ctx context.Context, createdAt time.Time) ([]GetExpiredPendingTransactionsRow, error)
	GetLedgerByOwnerID(ctx context.Context, arg GetLedgerByOwnerIDParams) (AccountLedgers, error)
	// Retrieves the platform cost details associated with a specific order ID.
	GetOrderPlatformCostByOrderID(ctx context.Context, orderID string) (OrderPlatformCosts, error)
	// Retrieves the platform cost details associated with a specific payment transaction.
	GetOrderPlatformCostByPaymentTxID(ctx context.Context, paymentTransactionID string) (OrderPlatformCosts, error)
	// =================================================================
	// Queries for `payment_methods` table
	// =================================================================
	GetPaymentMethodByID(ctx context.Context, id string) (PaymentMethods, error)
	GetPendingPaymentByOrderID(ctx context.Context, orderID sql.NullString) (Transactions, error)
	GetSettlementByID(ctx context.Context, id string) (ShopOrderSettlements, error)
	// Finds the settlement record for a specific shop order ID.
	GetSettlementByShopOrderID(ctx context.Context, shopOrderID string) (ShopOrderSettlements, error)
	// Tham số $1 (expired_before) sẽ được truyền từ code Go
	GetTransactionByID(ctx context.Context, id string) (Transactions, error)
	ListActivePaymentMethods(ctx context.Context) ([]PaymentMethods, error)
	// Finds settlements ready for automatic payout processing (status is FUNDS_HELD and holding period passed).
	// The '?' parameter should be calculated as NOW() - holding_period (e.g., NOW() - INTERVAL 7 DAY)
	ListEligibleSettlementsForProcessing(ctx context.Context, orderCompletedAt sql.NullTime) ([]ShopOrderSettlements, error)
	ListLedgerEntriesByLedgerIDPaged(ctx context.Context, arg ListLedgerEntriesByLedgerIDPagedParams) ([]LedgerEntries, error)
	// Use positive values for CREDIT, negative for DEBIT
	UpdateLedgerBalances(ctx context.Context, arg UpdateLedgerBalancesParams) error
	// Marks the settlement processing as failed (e.g., if accounting entries fail).
	UpdateSettlementStatusToFailed(ctx context.Context, id string) error
	// Marks the settlement as awaiting the holding period after successful delivery.
	UpdateSettlementStatusToFundsHeld(ctx context.Context, arg UpdateSettlementStatusToFundsHeldParams) error
	// Marks the settlement as completed after funds are moved to the shop's available balance.
	UpdateSettlementStatusToSettled(ctx context.Context, id string) error
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error
}

var _ Querier = (*Queries)(nil)
