// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :exec

INSERT INTO transactions (
  id, transaction_code, order_id, payment_method_id, amount, currency, type, status, notes
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateTransactionParams struct {
	ID              string             `json:"id"`
	TransactionCode string             `json:"transaction_code"`
	OrderID         sql.NullString     `json:"order_id"`
	PaymentMethodID string             `json:"payment_method_id"`
	Amount          string             `json:"amount"`
	Currency        string             `json:"currency"`
	Type            TransactionsType   `json:"type"`
	Status          TransactionsStatus `json:"status"`
	Notes           sql.NullString     `json:"notes"`
}

// =================================================================
// Queries for `transactions` table
// =================================================================
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, createTransaction,
		arg.ID,
		arg.TransactionCode,
		arg.OrderID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.Currency,
		arg.Type,
		arg.Status,
		arg.Notes,
	)
	return err
}

const getExpiredPendingTransactions = `-- name: GetExpiredPendingTransactions :many
SELECT id, order_id
FROM transactions
WHERE status = 'PENDING'
  AND type = 'PAYMENT'
  AND created_at < ?
`

type GetExpiredPendingTransactionsRow struct {
	ID      string         `json:"id"`
	OrderID sql.NullString `json:"order_id"`
}

func (q *Queries) GetExpiredPendingTransactions(ctx context.Context, createdAt time.Time) ([]GetExpiredPendingTransactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredPendingTransactions, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredPendingTransactionsRow
	for rows.Next() {
		var i GetExpiredPendingTransactionsRow
		if err := rows.Scan(&i.ID, &i.OrderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingPaymentByOrderID = `-- name: GetPendingPaymentByOrderID :one
SELECT id, transaction_code, order_id, payment_method_id, amount, currency, type, status, gateway_transaction_id, notes, created_at, processed_at FROM transactions
WHERE order_id = ? AND type = 'PAYMENT' AND status = 'PENDING'
LIMIT 1
`

func (q *Queries) GetPendingPaymentByOrderID(ctx context.Context, orderID sql.NullString) (Transactions, error) {
	row := q.db.QueryRowContext(ctx, getPendingPaymentByOrderID, orderID)
	var i Transactions
	err := row.Scan(
		&i.ID,
		&i.TransactionCode,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Status,
		&i.GatewayTransactionID,
		&i.Notes,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one

SELECT id, transaction_code, order_id, payment_method_id, amount, currency, type, status, gateway_transaction_id, notes, created_at, processed_at FROM transactions
WHERE id = ? LIMIT 1
`

// Tham số $1 (expired_before) sẽ được truyền từ code Go
func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transactions, error) {
	row := q.db.QueryRowContext(ctx, getTransactionByID, id)
	var i Transactions
	err := row.Scan(
		&i.ID,
		&i.TransactionCode,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.Currency,
		&i.Type,
		&i.Status,
		&i.GatewayTransactionID,
		&i.Notes,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET
  status = ?,
  processed_at = ?,
  gateway_transaction_id = ?,
  notes = ?
WHERE id = ?
`

type UpdateTransactionStatusParams struct {
	Status               TransactionsStatus `json:"status"`
	ProcessedAt          sql.NullTime       `json:"processed_at"`
	GatewayTransactionID sql.NullString     `json:"gateway_transaction_id"`
	Notes                sql.NullString     `json:"notes"`
	ID                   string             `json:"id"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionStatus,
		arg.Status,
		arg.ProcessedAt,
		arg.GatewayTransactionID,
		arg.Notes,
		arg.ID,
	)
	return err
}
