// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package db

import (
	"context"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :exec

INSERT INTO ledger_entries (
  ledger_id, transaction_id, amount, type, description
) VALUES (
  ?, ?, ?, ?, ?
)
`

type CreateLedgerEntryParams struct {
	LedgerID      string            `json:"ledger_id"`
	TransactionID string            `json:"transaction_id"`
	Amount        string            `json:"amount"`
	Type          LedgerEntriesType `json:"type"`
	Description   string            `json:"description"`
}

// =================================================================
// Queries for `ledger_entries` table
// =================================================================
func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) error {
	_, err := q.db.ExecContext(ctx, createLedgerEntry,
		arg.LedgerID,
		arg.TransactionID,
		arg.Amount,
		arg.Type,
		arg.Description,
	)
	return err
}

const listLedgerEntriesByLedgerIDPaged = `-- name: ListLedgerEntriesByLedgerIDPaged :many
SELECT id, ledger_id, transaction_id, amount, type, description, created_at FROM ledger_entries
WHERE ledger_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListLedgerEntriesByLedgerIDPagedParams struct {
	LedgerID string `json:"ledger_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByLedgerIDPaged(ctx context.Context, arg ListLedgerEntriesByLedgerIDPagedParams) ([]LedgerEntries, error) {
	rows, err := q.db.QueryContext(ctx, listLedgerEntriesByLedgerIDPaged, arg.LedgerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntries
	for rows.Next() {
		var i LedgerEntries
		if err := rows.Scan(
			&i.ID,
			&i.LedgerID,
			&i.TransactionID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
