// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type AccountLedgersOwnerType string

const (
	AccountLedgersOwnerTypeSHOP     AccountLedgersOwnerType = "SHOP"
	AccountLedgersOwnerTypePLATFORM AccountLedgersOwnerType = "PLATFORM"
)

func (e *AccountLedgersOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountLedgersOwnerType(s)
	case string:
		*e = AccountLedgersOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountLedgersOwnerType: %T", src)
	}
	return nil
}

type NullAccountLedgersOwnerType struct {
	AccountLedgersOwnerType AccountLedgersOwnerType `json:"account_ledgers_owner_type"`
	Valid                   bool                    `json:"valid"` // Valid is true if AccountLedgersOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountLedgersOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountLedgersOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountLedgersOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountLedgersOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountLedgersOwnerType), nil
}

type LedgerEntriesType string

const (
	LedgerEntriesTypeCREDIT LedgerEntriesType = "CREDIT"
	LedgerEntriesTypeDEBIT  LedgerEntriesType = "DEBIT"
)

func (e *LedgerEntriesType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntriesType(s)
	case string:
		*e = LedgerEntriesType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntriesType: %T", src)
	}
	return nil
}

type NullLedgerEntriesType struct {
	LedgerEntriesType LedgerEntriesType `json:"ledger_entries_type"`
	Valid             bool              `json:"valid"` // Valid is true if LedgerEntriesType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntriesType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntriesType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntriesType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntriesType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntriesType), nil
}

type PaymentMethodsType string

const (
	PaymentMethodsTypeONLINE  PaymentMethodsType = "ONLINE"
	PaymentMethodsTypeOFFLINE PaymentMethodsType = "OFFLINE"
)

func (e *PaymentMethodsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethodsType(s)
	case string:
		*e = PaymentMethodsType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethodsType: %T", src)
	}
	return nil
}

type NullPaymentMethodsType struct {
	PaymentMethodsType PaymentMethodsType `json:"payment_methods_type"`
	Valid              bool               `json:"valid"` // Valid is true if PaymentMethodsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethodsType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethodsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethodsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethodsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethodsType), nil
}

type ShopOrderSettlementsStatus string

const (
	ShopOrderSettlementsStatusPENDINGSETTLEMENT ShopOrderSettlementsStatus = "PENDING_SETTLEMENT"
	ShopOrderSettlementsStatusFUNDSHELD         ShopOrderSettlementsStatus = "FUNDS_HELD"
	ShopOrderSettlementsStatusSETTLED           ShopOrderSettlementsStatus = "SETTLED"
	ShopOrderSettlementsStatusFAILED            ShopOrderSettlementsStatus = "FAILED"
)

func (e *ShopOrderSettlementsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShopOrderSettlementsStatus(s)
	case string:
		*e = ShopOrderSettlementsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ShopOrderSettlementsStatus: %T", src)
	}
	return nil
}

type NullShopOrderSettlementsStatus struct {
	ShopOrderSettlementsStatus ShopOrderSettlementsStatus `json:"shop_order_settlements_status"`
	Valid                      bool                       `json:"valid"` // Valid is true if ShopOrderSettlementsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShopOrderSettlementsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ShopOrderSettlementsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShopOrderSettlementsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShopOrderSettlementsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShopOrderSettlementsStatus), nil
}

type TransactionsStatus string

const (
	TransactionsStatusPENDING TransactionsStatus = "PENDING"
	TransactionsStatusSUCCESS TransactionsStatus = "SUCCESS"
	TransactionsStatusFAILED  TransactionsStatus = "FAILED"
)

func (e *TransactionsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsStatus(s)
	case string:
		*e = TransactionsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsStatus: %T", src)
	}
	return nil
}

type NullTransactionsStatus struct {
	TransactionsStatus TransactionsStatus `json:"transactions_status"`
	Valid              bool               `json:"valid"` // Valid is true if TransactionsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsStatus), nil
}

type TransactionsType string

const (
	TransactionsTypePAYMENT TransactionsType = "PAYMENT"
	TransactionsTypeREFUND  TransactionsType = "REFUND"
	TransactionsTypePAYOUT  TransactionsType = "PAYOUT"
	TransactionsTypeDEPOSIT TransactionsType = "DEPOSIT"
)

func (e *TransactionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionsType(s)
	case string:
		*e = TransactionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionsType: %T", src)
	}
	return nil
}

type NullTransactionsType struct {
	TransactionsType TransactionsType `json:"transactions_type"`
	Valid            bool             `json:"valid"` // Valid is true if TransactionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionsType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionsType), nil
}

// Quản lý ví và số dư của Sàn và các Shop
type AccountLedgers struct {
	// UUID, Khóa chính của ví
	ID string `json:"id"`
	// ID của chủ sở hữu (shop_id hoặc Sàn)
	OwnerID   string                  `json:"owner_id"`
	OwnerType AccountLedgersOwnerType `json:"owner_type"`
	// Số dư khả dụng
	Balance string `json:"balance"`
	// Số dư đang chờ quyết toán
	PendingBalance string    `json:"pending_balance"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// Sổ cái kế toán, ghi lại mọi biến động số dư
type LedgerEntries struct {
	ID uint64 `json:"id"`
	// FK tới ví/sổ cái
	LedgerID string `json:"ledger_id"`
	// FK tới giao dịch gốc
	TransactionID string `json:"transaction_id"`
	// Số tiền thay đổi (âm/dương)
	Amount string `json:"amount"`
	// CREDIT (cộng tiền), DEBIT (trừ tiền)
	Type LedgerEntriesType `json:"type"`
	// Mô tả bút toán
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

// Ghi lại chi tiết các khoản chi phí Sàn chịu cho mỗi đơn hàng
type OrderPlatformCosts struct {
	ID uint64 `json:"id"`
	// ID của đơn hàng tổng
	OrderID string `json:"order_id"`
	// ID của giao dịch PAYMENT gốc
	PaymentTransactionID string `json:"payment_transaction_id"`
	// Tổng tiền voucher Sàn giảm giá ĐƠN HÀNG (Sàn chịu)
	SiteOrderVoucherDiscountAmount string `json:"site_order_voucher_discount_amount"`
	// Tổng tiền giảm giá từ ĐỢT KHUYẾN MÃI của Sàn (Sàn chịu)
	SitePromotionDiscountAmount string `json:"site_promotion_discount_amount"`
	// Tổng tiền Sàn giảm giá SHIP (bao gồm voucher và KM ship)
	SiteShippingDiscountAmount string `json:"site_shipping_discount_amount"`
	// Tổng tiền Sàn TRỢ GIÁ SẢN PHẨM cho toàn bộ đơn hàng
	TotalSiteFundedProductDiscount string    `json:"total_site_funded_product_discount"`
	CreatedAt                      time.Time `json:"created_at"`
}

// Quản lý các phương thức thanh toán
type PaymentMethods struct {
	// UUID, Khóa chính
	ID string `json:"id"`
	// Tên hiển thị cho người dùng (Ví dụ: "Ví MoMo")
	Name string `json:"name"`
	// Mã định danh (Ví dụ: "MOMO", "COD")
	Code string `json:"code"`
	// Loại hình thanh toán
	Type PaymentMethodsType `json:"type"`
	// Cho phép bật/tắt phương thức này
	IsActive bool `json:"is_active"`
}

// Theo dõi quyết toán và snapshot tài chính cho từng đơn hàng shop
type ShopOrderSettlements struct {
	ID string `json:"id"`
	// ID đơn hàng shop từ Order Service
	ShopOrderID string `json:"shop_order_id"`
	// ID giao dịch PAYMENT gốc
	OrderTransactionID string                     `json:"order_transaction_id"`
	Status             ShopOrderSettlementsStatus `json:"status"`
	// Tổng giá trị hàng hóa GỐC
	OrderSubtotal string `json:"order_subtotal"`
	// Giảm giá SP do Shop chịu
	ShopFundedProductDiscount string `json:"shop_funded_product_discount"`
	// Giảm giá SP do Sàn trợ giá (Sàn bù cho Shop)
	SiteFundedProductDiscount string `json:"site_funded_product_discount"`
	// Voucher của Shop (Shop chịu)
	ShopVoucherDiscount string `json:"shop_voucher_discount"`
	// Tiền Shop hỗ trợ ship (Shop chịu)
	ShopShippingDiscount string `json:"shop_shipping_discount"`
	// Số tiền giảm từ voucher SÀN (tiền hàng) đã được PHÂN BỔ cho đơn hàng shop này
	SiteOrderDiscount string `json:"site_order_discount"`
	// Tiền Sàn hỗ trợ ship (voucher ship) đã được PHÂN BỔ cho đơn hàng shop này
	SiteShippingDiscount string `json:"site_shipping_discount"`
	// Phí vận chuyển thực tế khách trả cho gói hàng này (Doanh thu của Sàn)
	ShippingFee string `json:"shipping_fee"`
	// Phí hoa hồng Sàn thu (trên giá gốc)
	CommissionFee string `json:"commission_fee"`
	// Số tiền thực tế Sàn chuyển vào ví Shop
	NetSettledAmount string       `json:"net_settled_amount"`
	OrderCompletedAt sql.NullTime `json:"order_completed_at"`
	SettledAt        sql.NullTime `json:"settled_at"`
}

// Ghi lại nhật ký các giao dịch tiền tệ thực tế
type Transactions struct {
	// UUID, Khóa chính
	ID string `json:"id"`
	// Mã giao dịch thân thiện, duy nhất
	TransactionCode string `json:"transaction_code"`
	// ID đơn hàng tổng. NULL nếu là Payout/Deposit
	OrderID sql.NullString `json:"order_id"`
	// FK tới payment_methods
	PaymentMethodID string `json:"payment_method_id"`
	// Số tiền thực tế khách trả HOẶC thực tế chuyển/nhận
	Amount               string             `json:"amount"`
	Currency             string             `json:"currency"`
	Type                 TransactionsType   `json:"type"`
	Status               TransactionsStatus `json:"status"`
	GatewayTransactionID sql.NullString     `json:"gateway_transaction_id"`
	Notes                sql.NullString     `json:"notes"`
	CreatedAt            time.Time          `json:"created_at"`
	ProcessedAt          sql.NullTime       `json:"processed_at"`
}
