// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_platform_costs.sql

package db

import (
	"context"
)

const createOrderPlatformCost = `-- name: CreateOrderPlatformCost :exec

INSERT INTO order_platform_costs (
  order_id,
  payment_transaction_id,
  site_order_voucher_discount_amount,
  site_promotion_discount_amount,
  site_shipping_discount_amount,
  total_site_funded_product_discount
) VALUES (
  ?, ?, ?, ?, ?, ?
)
`

type CreateOrderPlatformCostParams struct {
	OrderID                        string `json:"order_id"`
	PaymentTransactionID           string `json:"payment_transaction_id"`
	SiteOrderVoucherDiscountAmount string `json:"site_order_voucher_discount_amount"`
	SitePromotionDiscountAmount    string `json:"site_promotion_discount_amount"`
	SiteShippingDiscountAmount     string `json:"site_shipping_discount_amount"`
	TotalSiteFundedProductDiscount string `json:"total_site_funded_product_discount"`
}

// =================================================================
// Queries for `order_platform_costs` table (New Table)
// =================================================================
// Records the total costs incurred by the platform for a specific order payment.
func (q *Queries) CreateOrderPlatformCost(ctx context.Context, arg CreateOrderPlatformCostParams) error {
	_, err := q.db.ExecContext(ctx, createOrderPlatformCost,
		arg.OrderID,
		arg.PaymentTransactionID,
		arg.SiteOrderVoucherDiscountAmount,
		arg.SitePromotionDiscountAmount,
		arg.SiteShippingDiscountAmount,
		arg.TotalSiteFundedProductDiscount,
	)
	return err
}

const getOrderPlatformCostByOrderID = `-- name: GetOrderPlatformCostByOrderID :one
SELECT id, order_id, payment_transaction_id, site_order_voucher_discount_amount, site_promotion_discount_amount, site_shipping_discount_amount, total_site_funded_product_discount, created_at FROM order_platform_costs
WHERE order_id = ? LIMIT 1
`

// Retrieves the platform cost details associated with a specific order ID.
func (q *Queries) GetOrderPlatformCostByOrderID(ctx context.Context, orderID string) (OrderPlatformCosts, error) {
	row := q.db.QueryRowContext(ctx, getOrderPlatformCostByOrderID, orderID)
	var i OrderPlatformCosts
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentTransactionID,
		&i.SiteOrderVoucherDiscountAmount,
		&i.SitePromotionDiscountAmount,
		&i.SiteShippingDiscountAmount,
		&i.TotalSiteFundedProductDiscount,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderPlatformCostByPaymentTxID = `-- name: GetOrderPlatformCostByPaymentTxID :one
SELECT id, order_id, payment_transaction_id, site_order_voucher_discount_amount, site_promotion_discount_amount, site_shipping_discount_amount, total_site_funded_product_discount, created_at FROM order_platform_costs
WHERE payment_transaction_id = ? LIMIT 1
`

// Retrieves the platform cost details associated with a specific payment transaction.
func (q *Queries) GetOrderPlatformCostByPaymentTxID(ctx context.Context, paymentTransactionID string) (OrderPlatformCosts, error) {
	row := q.db.QueryRowContext(ctx, getOrderPlatformCostByPaymentTxID, paymentTransactionID)
	var i OrderPlatformCosts
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentTransactionID,
		&i.SiteOrderVoucherDiscountAmount,
		&i.SitePromotionDiscountAmount,
		&i.SiteShippingDiscountAmount,
		&i.TotalSiteFundedProductDiscount,
		&i.CreatedAt,
	)
	return i, err
}
