// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_methods.sql

package db

import (
	"context"
)

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one

SELECT id, name, code, type, is_active FROM payment_methods
WHERE id = ? AND is_active = TRUE
`

// =================================================================
// Queries for `payment_methods` table
// =================================================================
func (q *Queries) GetPaymentMethodByID(ctx context.Context, id string) (PaymentMethods, error) {
	row := q.db.QueryRowContext(ctx, getPaymentMethodByID, id)
	var i PaymentMethods
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Type,
		&i.IsActive,
	)
	return i, err
}

const listActivePaymentMethods = `-- name: ListActivePaymentMethods :many
SELECT id, name, code, type, is_active FROM payment_methods
WHERE is_active = TRUE
ORDER BY type, name
`

func (q *Queries) ListActivePaymentMethods(ctx context.Context) ([]PaymentMethods, error) {
	rows, err := q.db.QueryContext(ctx, listActivePaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethods
	for rows.Next() {
		var i PaymentMethods
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Type,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
