// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_order_settlements.sql

package db

import (
	"context"
	"database/sql"
)

const createShopOrderSettlement = `-- name: CreateShopOrderSettlement :exec

INSERT INTO shop_order_settlements (
  id,
  shop_order_id,
  order_transaction_id,
  status,
  order_subtotal,
  shop_funded_product_discount,
  site_funded_product_discount,
  shop_voucher_discount,
  shop_shipping_discount,
  shipping_fee,
  commission_fee,
  net_settled_amount
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateShopOrderSettlementParams struct {
	ID                        string                     `json:"id"`
	ShopOrderID               string                     `json:"shop_order_id"`
	OrderTransactionID        string                     `json:"order_transaction_id"`
	Status                    ShopOrderSettlementsStatus `json:"status"`
	OrderSubtotal             string                     `json:"order_subtotal"`
	ShopFundedProductDiscount string                     `json:"shop_funded_product_discount"`
	SiteFundedProductDiscount string                     `json:"site_funded_product_discount"`
	ShopVoucherDiscount       string                     `json:"shop_voucher_discount"`
	ShopShippingDiscount      string                     `json:"shop_shipping_discount"`
	ShippingFee               string                     `json:"shipping_fee"`
	CommissionFee             string                     `json:"commission_fee"`
	NetSettledAmount          string                     `json:"net_settled_amount"`
}

// =================================================================
// Queries for `shop_order_settlements` table
// =================================================================
// Creates the financial snapshot and settlement record for a shop order.
func (q *Queries) CreateShopOrderSettlement(ctx context.Context, arg CreateShopOrderSettlementParams) error {
	_, err := q.db.ExecContext(ctx, createShopOrderSettlement,
		arg.ID,
		arg.ShopOrderID,
		arg.OrderTransactionID,
		arg.Status,
		arg.OrderSubtotal,
		arg.ShopFundedProductDiscount,
		arg.SiteFundedProductDiscount,
		arg.ShopVoucherDiscount,
		arg.ShopShippingDiscount,
		arg.ShippingFee,
		arg.CommissionFee,
		arg.NetSettledAmount,
	)
	return err
}

const getSettlementByID = `-- name: GetSettlementByID :one
SELECT id, shop_order_id, order_transaction_id, status, order_subtotal, shop_funded_product_discount, site_funded_product_discount, shop_voucher_discount, shop_shipping_discount, shipping_fee, commission_fee, net_settled_amount, order_completed_at, settled_at FROM shop_order_settlements
WHERE id = ? LIMIT 1
`

func (q *Queries) GetSettlementByID(ctx context.Context, id string) (ShopOrderSettlements, error) {
	row := q.db.QueryRowContext(ctx, getSettlementByID, id)
	var i ShopOrderSettlements
	err := row.Scan(
		&i.ID,
		&i.ShopOrderID,
		&i.OrderTransactionID,
		&i.Status,
		&i.OrderSubtotal,
		&i.ShopFundedProductDiscount,
		&i.SiteFundedProductDiscount,
		&i.ShopVoucherDiscount,
		&i.ShopShippingDiscount,
		&i.ShippingFee,
		&i.CommissionFee,
		&i.NetSettledAmount,
		&i.OrderCompletedAt,
		&i.SettledAt,
	)
	return i, err
}

const getSettlementByShopOrderID = `-- name: GetSettlementByShopOrderID :one
SELECT id, shop_order_id, order_transaction_id, status, order_subtotal, shop_funded_product_discount, site_funded_product_discount, shop_voucher_discount, shop_shipping_discount, shipping_fee, commission_fee, net_settled_amount, order_completed_at, settled_at FROM shop_order_settlements
WHERE shop_order_id = ? LIMIT 1
`

// Finds the settlement record for a specific shop order ID.
func (q *Queries) GetSettlementByShopOrderID(ctx context.Context, shopOrderID string) (ShopOrderSettlements, error) {
	row := q.db.QueryRowContext(ctx, getSettlementByShopOrderID, shopOrderID)
	var i ShopOrderSettlements
	err := row.Scan(
		&i.ID,
		&i.ShopOrderID,
		&i.OrderTransactionID,
		&i.Status,
		&i.OrderSubtotal,
		&i.ShopFundedProductDiscount,
		&i.SiteFundedProductDiscount,
		&i.ShopVoucherDiscount,
		&i.ShopShippingDiscount,
		&i.ShippingFee,
		&i.CommissionFee,
		&i.NetSettledAmount,
		&i.OrderCompletedAt,
		&i.SettledAt,
	)
	return i, err
}

const listEligibleSettlementsForProcessing = `-- name: ListEligibleSettlementsForProcessing :many
SELECT id, shop_order_id, order_transaction_id, status, order_subtotal, shop_funded_product_discount, site_funded_product_discount, shop_voucher_discount, shop_shipping_discount, shipping_fee, commission_fee, net_settled_amount, order_completed_at, settled_at FROM shop_order_settlements
WHERE status = 'FUNDS_HELD' AND order_completed_at IS NOT NULL AND order_completed_at <= ?
`

// Finds settlements ready for automatic payout processing (status is FUNDS_HELD and holding period passed).
// The '?' parameter should be calculated as NOW() - holding_period (e.g., NOW() - INTERVAL 7 DAY)
func (q *Queries) ListEligibleSettlementsForProcessing(ctx context.Context, orderCompletedAt sql.NullTime) ([]ShopOrderSettlements, error) {
	rows, err := q.db.QueryContext(ctx, listEligibleSettlementsForProcessing, orderCompletedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopOrderSettlements
	for rows.Next() {
		var i ShopOrderSettlements
		if err := rows.Scan(
			&i.ID,
			&i.ShopOrderID,
			&i.OrderTransactionID,
			&i.Status,
			&i.OrderSubtotal,
			&i.ShopFundedProductDiscount,
			&i.SiteFundedProductDiscount,
			&i.ShopVoucherDiscount,
			&i.ShopShippingDiscount,
			&i.ShippingFee,
			&i.CommissionFee,
			&i.NetSettledAmount,
			&i.OrderCompletedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSettlementStatusToFailed = `-- name: UpdateSettlementStatusToFailed :exec
UPDATE shop_order_settlements
SET
  status = 'FAILED'
WHERE id = ?
`

// Marks the settlement processing as failed (e.g., if accounting entries fail).
func (q *Queries) UpdateSettlementStatusToFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSettlementStatusToFailed, id)
	return err
}

const updateSettlementStatusToFundsHeld = `-- name: UpdateSettlementStatusToFundsHeld :exec
UPDATE shop_order_settlements
SET
  status = 'FUNDS_HELD',
  order_completed_at = ? -- Pass the completion timestamp from Order Service
WHERE shop_order_id = ?
`

type UpdateSettlementStatusToFundsHeldParams struct {
	OrderCompletedAt sql.NullTime `json:"order_completed_at"`
	ShopOrderID      string       `json:"shop_order_id"`
}

// Marks the settlement as awaiting the holding period after successful delivery.
func (q *Queries) UpdateSettlementStatusToFundsHeld(ctx context.Context, arg UpdateSettlementStatusToFundsHeldParams) error {
	_, err := q.db.ExecContext(ctx, updateSettlementStatusToFundsHeld, arg.OrderCompletedAt, arg.ShopOrderID)
	return err
}

const updateSettlementStatusToSettled = `-- name: UpdateSettlementStatusToSettled :exec
UPDATE shop_order_settlements
SET
  status = 'SETTLED',
  settled_at = NOW()
WHERE id = ?
`

// Marks the settlement as completed after funds are moved to the shop's available balance.
func (q *Queries) UpdateSettlementStatusToSettled(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateSettlementStatusToSettled, id)
	return err
}
