// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// =================================================================
	// I. API CHO SHOP (Shop-facing APIs)
	// =================================================================
	// Tác dụng: Lấy thông tin ví của Shop (API: GET /shop/overview, /shop/wallet/summary)
	GetLedgerByOwnerID(ctx context.Context, ownerID string) (AccountLedgers, error)
	// Tác dụng: Lấy Tổng chi phí Sàn (API: GET /platform/overview)
	GetPlatformCostSummary(ctx context.Context, arg GetPlatformCostSummaryParams) (GetPlatformCostSummaryRow, error)
	// Tác dụng: Vẽ biểu đồ Chi phí Sàn (API: GET /platform/finance/revenue-timeseries)
	GetPlatformCostTimeSeries(ctx context.Context, arg GetPlatformCostTimeSeriesParams) ([]GetPlatformCostTimeSeriesRow, error)
	// =================================================================
	// II. API CHO SÀN (Platform-facing APIs)
	// =================================================================
	// Tác dụng: Lấy Doanh thu & Chi phí của Sàn (API: GET /platform/overview)
	GetPlatformRevenueSummary(ctx context.Context, arg GetPlatformRevenueSummaryParams) (GetPlatformRevenueSummaryRow, error)
	// Tác dụng: Vẽ biểu đồ Doanh thu Sàn (API: GET /platform/finance/revenue-timeseries)
	GetPlatformRevenueTimeSeries(ctx context.Context, arg GetPlatformRevenueTimeSeriesParams) ([]GetPlatformRevenueTimeSeriesRow, error)
	// Tác dụng: Thống kê tổng tiền đối soát của Shop (API: GET /shop/wallet/summary)
	// ĐÃ SỬA: Sửa 'ANY(sqlc.slice())' thành 'IN (sqlc.slice())'
	GetShopSettlementStatsByOrderIDs(ctx context.Context, shopOrderIds []string) (GetShopSettlementStatsByOrderIDsRow, error)
	// Tác dụng: Lấy thông tin đối soát của Shop (API: GET /shop/settlements)
	// ĐÃ SỬA: Sửa 'ANY(sqlc.slice())' thành 'IN (sqlc.slice())'
	GetShopSettlementsByOrderIDs(ctx context.Context, shopOrderIds []string) ([]ShopOrderSettlements, error)
	// Tác dụng: Lấy trạng thái thanh toán cho 1 loạt đơn hàng (Dùng nội bộ)
	// ĐÃ SỬA: Sửa 'ANY(sqlc.slice())' thành 'IN (sqlc.slice())'
	GetTransactionStatusesByOrderIDs(ctx context.Context, orderIds []sql.NullString) ([]GetTransactionStatusesByOrderIDsRow, error)
	// Tác dụng: Lấy lịch sử giao dịch của 1 ví cụ thể (API: GET /platform/finance/ledgers/{id}/entries)
	ListLedgerEntriesByLedgerID(ctx context.Context, arg ListLedgerEntriesByLedgerIDParams) ([]LedgerEntries, error)
	// Tác dụng: Lấy lịch sử giao dịch ví của Shop (API: GET /shop/wallet/ledger-entries)
	ListLedgerEntriesByOwnerID(ctx context.Context, arg ListLedgerEntriesByOwnerIDParams) ([]LedgerEntries, error)
	// Tác dụng: Lấy tất cả ví trên Sàn (API: GET /platform/finance/ledgers)
	// ĐÃ SỬA: Bỏ các cast '::text'
	ListPlatformLedgers(ctx context.Context, arg ListPlatformLedgersParams) ([]AccountLedgers, error)
	// Tác dụng: Lấy tất cả bản ghi đối soát (API: GET /platform/finance/settlements)
	// ĐÃ SỬA: Bỏ các cast '::text'
	ListPlatformSettlements(ctx context.Context, arg ListPlatformSettlementsParams) ([]ShopOrderSettlements, error)
	// Tác dụng: Lấy tất cả giao dịch (API: GET /platform/finance/transactions)
	// ĐÃ SỬA: Bỏ các cast '::text'
	ListPlatformTransactions(ctx context.Context, arg ListPlatformTransactionsParams) ([]Transactions, error)
}

var _ Querier = (*Queries)(nil)
